# hana configuration

[tiling]
enabled = 1  # 1 -> true, 0 -> false

# Behavior
layout = "master_left" # Options: "master_left", "monocle", "grid"

master_width_factor = 50 # %
master_count = 1

# Appearance
border_width = 2
border_focused = "#FF0000"
border_normal = "#660000"

gaps = 10

[Keybindings]
# Substitutions
Mod = "Super" # Mod1/Alt, Mod4/Super, Shift

# Commands
Mod+Return = "ghostty"
Mod+Shift+q = "kill"

# Tiling
Mod+t       = "toggle_layout"
Mod+h       = "decrease_master"
Mod+l       = "increase_master"
Mod+i       = "increase_master_count"
Mod+d       = "decrease_master_count"
Mod+Shift+t = "toggle_tiling"
