// Tiling window management — delegates to layout modules.

const std        = @import("std");
const defs       = @import("defs");
const xcb        = defs.xcb;
const WM         = defs.WM;
const utils      = @import("utils");
const constants  = @import("constants");
const focus      = @import("focus");
const workspaces = @import("workspaces");
const bar        = @import("bar");
const Tracking   = @import("tracking").Tracking;
const debug      = @import("debug");
const dpi        = @import("dpi");
const layouts    = @import("layouts");

// layout_flags is a dedicated build-options module generated by build.zig
// after discoverModules runs.  It contains one has_X bool per known layout
// name, reflecting which files are actually present on disk.  Using a
// separate module (not build_options) gives it an independent cache key so
// adding or removing a layout file invalidates only layout-related caches.
const layout_flags = @import("layout_flags");

const LayoutStub = struct {
    pub fn tileWithOffset(
        _: *xcb.xcb_connection_t,
        _: anytype,
        _: []const u32,
        _: u16, _: u16, _: u16,
    ) void {}
};

const master_layout    = if (layout_flags.has_master)    @import("master")    else LayoutStub;
const monocle_layout   = if (layout_flags.has_monocle)   @import("monocle")   else LayoutStub;
const grid_layout      = if (layout_flags.has_grid)      @import("grid")      else LayoutStub;
const fibonacci_layout = if (layout_flags.has_fibonacci) @import("fibonacci") else LayoutStub;

const MAX_MASTER_WIDTH: f32  = 0.95;
// Stack-local buffer size for per-retile workspace window list.
const MAX_WS_WINDOWS: usize = 128;

pub const Layout = enum { master, monocle, grid, fibonacci };

/// Ordered list of layouts that are actually present on disk, built at
/// comptime from build_options.  toggleLayout / toggleLayoutReverse walk
/// this list so missing layouts are never visited during cycling.
/// A compile error fires if every layout file has been removed.
const LAYOUT_CYCLE: []const Layout = blk: {
    var list: []const Layout = &.{};
    if (layout_flags.has_master)    list = list ++ &[_]Layout{.master};
    if (layout_flags.has_monocle)   list = list ++ &[_]Layout{.monocle};
    if (layout_flags.has_grid)      list = list ++ &[_]Layout{.grid};
    if (layout_flags.has_fibonacci) list = list ++ &[_]Layout{.fibonacci};
    if (list.len == 0) @compileError("No tiling layouts found. Add at least one .zig file to src/tiling/layouts/.");
    break :blk list;
};

/// True when the module file for `layout` was present at build time.
pub fn isLayoutAvailable(layout: Layout) bool {
    return switch (layout) {
        .master    => layout_flags.has_master,
        .monocle   => layout_flags.has_monocle,
        .grid      => layout_flags.has_grid,
        .fibonacci => layout_flags.has_fibonacci,
    };
}

fn stepCycle(current: Layout, comptime forward: bool) Layout {
    for (LAYOUT_CYCLE, 0..) |l, i| {
        if (l == current) return LAYOUT_CYCLE[
            if (forward) (i + 1) % LAYOUT_CYCLE.len
            else         (LAYOUT_CYCLE.len + i - 1) % LAYOUT_CYCLE.len
        ];
    }
    return LAYOUT_CYCLE[0]; // current is a missing layout — jump to first available
}

// Variation enums are defined in defs.zig to allow config.zig to parse them
// without a circular import. Re-exported here for convenience.
pub const MasterVariation  = defs.MasterVariation;
pub const MonocleVariation = defs.MonocleVariation;
pub const GridVariation    = defs.GridVariation;

/// Stores the active variation for every layout independently.
/// Each layout remembers its last variation when the user switches away and back.
pub const LayoutVariations = struct {
    master:  MasterVariation  = .lifo,
    monocle: MonocleVariation = .gapless,
    grid:    GridVariation    = .rigid,
};

// State

pub const State = struct {
    allocator:        std.mem.Allocator,
    enabled:          bool,
    layout:           Layout,
    layout_variations: LayoutVariations,
    /// 3-character indicator shown in the bar for the fibonacci layout (which has no variations).
    /// Configurable in config.toml; defaults to "NUL".
    fibonacci_indicator: [3]u8,
    master_side:      defs.MasterSide,
    master_width:     f32,
    master_count:     u8,
    gaps:             u16,
    border_width:     u16,
    border_focused:   u32,
    border_unfocused: u32,
    windows:          Tracking,
    dirty:            bool,
    /// Tracks the last geometry sent to the X server per window.
    /// Populated/updated by configureSafe via layouts.armGeomCache.
    /// Lets retile skip configure_window calls for unchanged windows.
    last_retile_screen: utils.Rect,
    geom_cache:       std.AutoHashMapUnmanaged(u32, utils.Rect),
    /// Tracks the last border pixel color sent to the X server per window.
    /// Populated in addWindow (prevents duplicate send on immediate retile)
    /// and kept current by updateBorders / updateBorderForFocusChange.
    border_cache:     std.AutoHashMapUnmanaged(u32, u32),

    pub inline fn margins(self: *const State) utils.Margins {
        return .{ .gap = self.gaps, .border = self.border_width };
    }

    pub inline fn borderColor(self: *const State, wm: *const WM, win: u32) u32 {
        if (wm.fullscreen.isFullscreen(win)) return 0;
        return if (wm.focused_window == win) self.border_focused else self.border_unfocused;
    }

    pub fn deinit(self: *State) void {
        self.windows.deinit();
        self.geom_cache.deinit(self.allocator);
        self.border_cache.deinit(self.allocator);
    }
};

// Module singleton

var g_state: ?State = null;

pub fn getState() ?*State { return if (g_state) |*s| s else null; }

// Config

/// Compute the normalised master width ratio from the current WM configuration.
/// Returns a value in [MIN_MASTER_WIDTH, MAX_MASTER_WIDTH].
fn computeMasterWidth(wm: *WM) f32 {
    const raw = dpi.scaleMasterWidth(wm.config.tiling.master_width);
    if (raw < 0) {
        const ratio = -raw / @as(f32, @floatFromInt(wm.screen.width_in_pixels));
        return @min(MAX_MASTER_WIDTH, @max(defs.MIN_MASTER_WIDTH, ratio));
    }
    return raw;
}

/// Build a complete State from the current WM configuration.
fn buildState(wm: *WM) State {
    const screen_height = wm.screen.height_in_pixels;

    return .{
        .allocator        = wm.allocator,
        .enabled          = wm.config.tiling.enabled,
        .layout           = blk: {
            const requested = std.meta.stringToEnum(Layout, wm.config.tiling.layout)
                orelse LAYOUT_CYCLE[0];
            // If the config names a layout whose file no longer exists, fall
            // back to the first available one rather than leaving the enum in
            // an unreachable state.
            break :blk if (isLayoutAvailable(requested)) requested else LAYOUT_CYCLE[0];
        },
        .layout_variations = .{
            .master  = wm.config.tiling.master_variation,
            .monocle = wm.config.tiling.monocle_variation,
            .grid    = wm.config.tiling.grid_variation,
        },
        .fibonacci_indicator = wm.config.tiling.fibonacci_indicator,
        .master_side      = wm.config.tiling.master_side,
        .master_width     = computeMasterWidth(wm),
        .master_count     = wm.config.tiling.master_count,
        .gaps             = dpi.scaleGaps(wm.config.tiling.gaps, wm.dpi_info.scale_factor, screen_height),
        .border_width     = dpi.scaleBorderWidth(wm.config.tiling.border_width, wm.dpi_info.scale_factor, screen_height),
        .border_focused   = wm.config.tiling.border_focused,
        .border_unfocused = wm.config.tiling.border_unfocused,
        .windows          = Tracking.init(wm.allocator),
        .dirty            = false,
        .last_retile_screen = .{ .x = 0, .y = 0, .width = 0, .height = 0 },
        .geom_cache       = .{},
        .border_cache     = .{},
    };
}

pub fn init(wm: *WM) void {
    g_state = buildState(wm);
}

pub fn deinit() void {
    if (g_state) |*s| s.deinit();
    g_state = null;
}

pub fn reloadConfig(wm: *WM) void {
    const s = getState() orelse return;

    // Preserve runtime tracking state; rebuild everything else from config.
    const saved_windows = s.windows;

    // Config changes (gaps, border width, colors) invalidate both caches.
    s.geom_cache.deinit(s.allocator);
    s.border_cache.deinit(s.allocator);

    g_state = buildState(wm);
    const ns = getState().?; // g_state is non-null immediately after buildState
    ns.windows = saved_windows;

    // On config reload, reset all workspace layouts to the new default so
    // stale per-workspace selections don't persist across a config change.
    // This mirrors the expectation that reload = "apply new config cleanly".
    if (workspaces.getState()) |ws_state| {
        for (ws_state.workspaces) |*ws| ws.layout = ns.layout;
    }

    if (ns.enabled) {
        // Push the new border width to every tracked window.  retileCurrentWorkspace
        // only updates geometry (x/y/width/height); BORDER_WIDTH is sent once in
        // addWindow and never again, so existing windows keep their old value after
        // a reload unless we explicitly resend it here.
        // We do this before retileCurrentWorkspace so the geometry recalculation
        // already accounts for the new border width.
        for (ns.windows.items()) |win| {
            _ = xcb.xcb_configure_window(wm.conn, win,
                xcb.XCB_CONFIG_WINDOW_BORDER_WIDTH, &[_]u32{ns.border_width});
        }
        retileCurrentWorkspace(wm);
    }
}

// Window management

pub fn addWindow(wm: *WM, window_id: u32) void {
    std.debug.assert(window_id != 0);
    const s = getState() orelse return;
    if (!s.enabled) return;

    // In master layout with FIFO variation new windows go to the front
    // (master position); all other cases append to the stack end.
    if (s.layout == .master and s.layout_variations.master == .fifo) {
        s.windows.addFront(window_id) catch |err| { debug.logError(err, window_id); return; };
    } else {
        s.windows.add(window_id) catch |err| { debug.logError(err, window_id); return; };
    }
    s.dirty = true;

    // Set BORDER_PIXEL only — EVENT_MASK was already applied by handleMapRequest,
    // so sending it again here is a redundant attribute update.
    const border_color = s.borderColor(wm, window_id);
    _ = xcb.xcb_change_window_attributes(wm.conn, window_id,
        xcb.XCB_CW_BORDER_PIXEL, &[_]u32{border_color});
    _ = xcb.xcb_configure_window(wm.conn, window_id,
        xcb.XCB_CONFIG_WINDOW_BORDER_WIDTH, &[_]u32{s.border_width});

    // Pre-populate the border cache so the retileCurrentWorkspace call that
    // immediately follows this (in setupTiling) does not re-send the border
    // pixel for this window — it was just set above.
    s.border_cache.put(s.allocator, window_id, border_color) catch {};

}

pub fn removeWindow(window_id: u32) void {
    const s = getState() orelse return;
    if (s.windows.remove(window_id)) {
        s.dirty = true;
        _ = s.geom_cache.remove(window_id);
        _ = s.border_cache.remove(window_id);
    }
}

/// Evict a window from the geometry cache without removing it from tiling.
///
/// Call this whenever a window's position is changed outside of the normal
/// retile path (e.g. pushed offscreen during fullscreen enter, or expanded
/// to cover the full screen) so that the next retileCurrentWorkspace does
/// not find a stale cache hit and silently skip the configure_window call.
pub fn invalidateGeomCache(window_id: u32) void {
    const s = getState() orelse return;
    _ = s.geom_cache.remove(window_id);
}

/// Restore windows on the current workspace to their cached tiled positions,
/// bypassing the layout algorithm entirely.
///
/// Returns true  — cache is valid and positions have been replayed.
/// Returns false — cache is stale or incomplete; caller must fall back to
///                 retileCurrentWorkspace so the layout reruns.
///
/// The cache is considered stale when:
///   • dirty flag is set (window added/removed/layout changed)
///   • any window on this workspace is absent from the cache
///   • the screen area (bar height/position) differs from when the cache
///     was last populated — handles bar visibility toggles on other workspaces
///     including when the current workspace was fullscreen at toggle time
pub fn restoreWorkspaceGeom(wm: *WM) bool {
    const s = getState() orelse return false;
    if (s.dirty) return false;

    var ws_buf: [MAX_WS_WINDOWS]u32 = undefined;
    const ws_count = filterWorkspaceWindows(s, &ws_buf);
    const ws_windows = ws_buf[0..ws_count];
    if (ws_windows.len == 0) return true;

    // If bar height or position changed since the cache was last written, the
    // stored rects are computed for a different screen area and must not be
    // replayed.  This is the canonical fix for bar-toggle-while-fullscreen:
    // no matter how bar state was changed or through which code path, the
    // screen rect comparison catches it without requiring external hooks.
    const current_screen = calculateScreenArea(wm);
    if (current_screen.x      != s.last_retile_screen.x      or
        current_screen.y      != s.last_retile_screen.y      or
        current_screen.width  != s.last_retile_screen.width  or
        current_screen.height != s.last_retile_screen.height)
    {
        return false;
    }

    // Verify every window is cached and collect rects in one pass — a single
    // miss aborts before any XCB calls are sent.  Using a local rect buffer
    // halves the number of hash lookups versus a separate contains + get pass.
    var rects: [MAX_WS_WINDOWS]utils.Rect = undefined;
    for (ws_windows, 0..) |win, i| {
        rects[i] = s.geom_cache.get(win) orelse return false;
    }

    // All rects confirmed present — replay cached positions.
    for (ws_windows, 0..) |win, i| {
        utils.configureWindow(wm.conn, win, rects[i]);
    }
    updateBorders(wm, ws_windows);
    return true;
}

pub inline fn isWindowTiled(window_id: u32) bool {
    const s = getState() orelse return false;
    return s.windows.contains(window_id);
}

/// Return the cached geometry for `window_id` if present.
///
/// This is a zero-cost lookup into the tiling state's geometry cache and
/// avoids an X round-trip. Returns null when the window has no cached rect
/// (e.g. fullscreen windows or after an explicit invalidate).
pub fn getCachedGeom(window_id: u32) ?utils.Rect {
    const s = getState() orelse return null;
    return s.geom_cache.get(window_id);
}

// Layout dispatch

fn dispatchLayout(layout: Layout, conn: *xcb.xcb_connection_t, s: *State, wins: []const u32, w: u16, h: u16, y: u16) void {
    switch (layout) {
        .master    => master_layout.tileWithOffset(conn, s, wins, w, h, y),
        .monocle   => monocle_layout.tileWithOffset(conn, s, wins, w, h, y),
        .grid      => grid_layout.tileWithOffset(conn, s, wins, w, h, y),
        .fibonacci => fibonacci_layout.tileWithOffset(conn, s, wins, w, h, y),
    }
}

// Screen area

fn calculateScreenArea(wm: *WM) utils.Rect {
    const bar_height: u16 = if (bar.isVisible()) bar.getBarHeight() else 0;
    const bar_at_bottom   = wm.config.bar.vertical_position == .bottom;
    return .{
        .x      = 0,
        .y      = if (bar_at_bottom) 0 else @intCast(bar_height),
        .width  = wm.screen.width_in_pixels,
        .height = wm.screen.height_in_pixels - bar_height,
    };
}

// Retiling

/// Recalculate and send geometry for every tiled window on every workspace.
///
/// Called after bar visibility or position changes so that all offscreen
/// windows on inactive workspaces already have the correct size before the
/// user switches to them — preventing the resize flicker that would otherwise
/// occur at workspace-switch time.
///
/// The current workspace is skipped: bar.setBarState already called
/// retileCurrentWorkspace for it.  Fullscreen workspaces are also skipped:
/// their sibling windows are parked offscreen and will be retiled when the
/// user exits fullscreen, at which point bar state is already correct.
pub fn retileAllWorkspaces(wm: *WM) void {
    const s = getState() orelse return;
    if (!s.enabled) return;

    const screen     = calculateScreenArea(wm);
    const ws_count   = workspaces.getWorkspaceCount();
    const current_ws = workspaces.getCurrentWorkspace() orelse return;

    // Resolve per-workspace layout state once before the loop — the pointer
    // is identical on every iteration and calling getState() in a hot loop
    // adds unnecessary indirection on each workspace dispatch.
    const ws_state_opt = if (!wm.config.tiling.global_layout) workspaces.getState() else null;

    layouts.armGeomCache(&s.geom_cache, s.allocator);

    // One pass: bucket every tiled window into its workspace slot — O(windows)
    // instead of the previous O(workspaces × windows) double loop.
    // MAX_WS must be at least as large as the maximum workspace count; 32 is
    // more than enough for any realistic config and costs 32×128×4 = 16 KB of
    // stack (the old code used a fresh 128-element stack buffer per workspace
    // iteration anyway, so the total stack pressure is actually lower now).
    const MAX_WS: usize = 32;
    const effective_ws = @min(ws_count, MAX_WS);
    var bufs: [MAX_WS][MAX_WS_WINDOWS]u32 = undefined;
    var lens: [MAX_WS]usize               = @splat(0);

    for (s.windows.items()) |win| {
        const ws_idx = workspaces.getWorkspaceForWindow(win) orelse continue;
        if (ws_idx >= effective_ws) continue;
        if (lens[ws_idx] < MAX_WS_WINDOWS) {
            bufs[ws_idx][lens[ws_idx]] = win;
            lens[ws_idx] += 1;
        }
    }

    const w: u16 = screen.width;
    const h: u16 = screen.height;
    const y: u16 = @intCast(screen.y);

    var ws_idx: u8 = 0;
    while (ws_idx < effective_ws) : (ws_idx += 1) {
        if (ws_idx == current_ws) continue;
        if (wm.fullscreen.getForWorkspace(ws_idx)) |_| continue;

        const ws_windows = bufs[ws_idx][0..lens[ws_idx]];
        if (ws_windows.len == 0) continue;

        const ws_layout: Layout = if (ws_state_opt) |ws_state|
            if (ws_idx < ws_state.workspaces.len) ws_state.workspaces[ws_idx].layout else s.layout
        else
            s.layout;

        dispatchLayout(ws_layout, wm.conn, s, ws_windows, w, h, y);
        updateBorders(wm, ws_windows);
    }

    layouts.disarmGeomCache();

    // Update last_retile_screen so restoreWorkspaceGeom's screen-rect check
    // passes for all workspaces after this call.
    s.last_retile_screen = screen;
}

pub fn retileIfDirty(wm: *WM) void {
    const s = getState() orelse return;
    if (!s.enabled or !s.dirty) return;
    retile(wm, calculateScreenArea(wm));
    s.dirty = false;
}

pub fn retileCurrentWorkspace(wm: *WM) void {
    const s = getState() orelse return;
    if (!s.enabled) return;
    retile(wm, calculateScreenArea(wm));
    s.dirty = false;
}

/// Retile a specific *inactive* workspace so its geometry cache is correct
/// before the user switches to it.
///
/// When a window on a non-current workspace is destroyed, `removeWindow` marks
/// the tiling state dirty but never retiles (no retile is safe to do without a
/// server grab, and the grab in `unmanageWindow` only retiles the current
/// workspace in the `was_focused` branch).  The dirty flag causes
/// `restoreWorkspaceGeom` to fail at switch time, forcing the layout algorithm
/// to run mid-switch — which can produce a visible flash as the remaining window
/// jumps from its old position to its new one.
///
/// This function pre-computes the correct geometry for the inactive workspace:
///   1. Temporarily sets `ws_state.current` to `ws_idx` so `retile` filters
///      the right window set and populates the geom cache.
///   2. Queues configure_window calls to push those windows back to OFFSCREEN_X
///      (they must not be visible while their workspace is inactive), but does
///      NOT invalidate the cache entries — the cache retains the correct
///      on-screen positions.
///   3. Restores `ws_state.current`.
///
/// After this call, `restoreWorkspaceGeom` will find `dirty=false` and a
/// fully-populated cache at switch time, take the fast path, and emit only a
/// single set of configure_window calls — no layout algorithm run, no flash.
///
/// MUST be called inside a server grab: the retile transiently moves windows
/// to their on-screen positions so the compositor must be frozen for the
/// duration.  The grab in `unmanageWindow` satisfies this requirement.
pub fn retileInactiveWorkspace(wm: *WM, ws_idx: u8) void {
    const s = getState() orelse return;
    if (!s.enabled) return;

    const ws_state = workspaces.getState() orelse return;
    if (ws_idx >= ws_state.workspaces.len) return;

    // Safety: if somehow called for the current workspace, delegate normally.
    if (ws_idx == ws_state.current) {
        retileCurrentWorkspace(wm);
        return;
    }

    // Temporarily pretend this is the current workspace so retile's window
    // filter and the layout algorithm operate on the right window set.
    const saved_current = ws_state.current;
    ws_state.current = ws_idx;
    retile(wm, calculateScreenArea(wm));
    s.dirty = false;
    ws_state.current = saved_current;

    // The retile above queued configure_window calls that move workspace ws_idx
    // windows to their on-screen tiled positions.  Push them back offscreen so
    // they are not visible while their workspace is inactive.
    //
    // Critically, we do NOT call invalidateGeomCache here.  The geom cache now
    // holds the correct on-screen tiled rects for all remaining windows.  At
    // switch time, restoreWorkspaceGeom will find dirty=false, a complete cache,
    // and a matching screen rect — it will take the fast path and replay these
    // positions in a single batch, with no layout algorithm run and no flash.
    for (ws_state.workspaces[ws_idx].windows.items()) |win| {
        _ = xcb.xcb_configure_window(wm.conn, win,
            xcb.XCB_CONFIG_WINDOW_X,
            &[_]u32{@bitCast(@as(i32, constants.OFFSCREEN_X_POSITION))});
    }
}

fn retile(wm: *WM, screen: utils.Rect) void {
    const s = getState() orelse return;

    const current_ws = workspaces.getCurrentWorkspace() orelse return;
    if (wm.fullscreen.getForWorkspace(current_ws)) |_| return;

    // Collect windows for the current workspace into a stack-local buffer.
    var ws_buf: [MAX_WS_WINDOWS]u32 = undefined;
    const ws_count = filterWorkspaceWindows(s, &ws_buf);
    const ws_windows = ws_buf[0..ws_count];
    if (ws_windows.len == 0) return;

    const w = screen.width;
    const h = screen.height;
    const y: u16 = @intCast(screen.y);

    // Arm the geometry cache so configureSafe can skip windows whose
    // position/size hasn't changed since the last retile.
    layouts.armGeomCache(&s.geom_cache, s.allocator);
    dispatchLayout(s.layout, wm.conn, s, ws_windows, w, h, y);
    layouts.disarmGeomCache();

    // Record the screen area used for this retile.  restoreWorkspaceGeom
    // compares this against the current screen area on the next workspace
    // switch — a mismatch (bar toggled, position changed, etc.) means the
    // cached rects are stale and a full retile is needed.
    s.last_retile_screen = screen;

    updateBorders(wm, ws_windows);
}

fn updateBorders(wm: *WM, ws_windows: []const u32) void {
    const s = getState() orelse return;
    for (ws_windows) |win| {
        const color = s.borderColor(wm, win);
        // Skip if the border pixel was already sent with this exact color
        // (e.g. pre-populated by addWindow or a previous retile/focus change).
        if (s.border_cache.get(win)) |cached| {
            if (cached == color) continue;
        }
        _ = xcb.xcb_change_window_attributes(wm.conn, win, xcb.XCB_CW_BORDER_PIXEL, &[_]u32{color});
        s.border_cache.put(s.allocator, win, color) catch {};
    }
}

// Focus border updates

pub fn updateWindowFocus(wm: *WM, old_focused: ?u32, new_focused: ?u32) void {
    const s = getState() orelse return;
    for ([2]?u32{ old_focused, new_focused }) |opt| {
        const win = opt orelse continue;
        if (!s.windows.contains(win)) continue;
        const color = s.borderColor(wm, win);
        // Skip the XCB call if the border is already this color — same guard
        // used by updateBorders.  Focus transitions that do not change the
        // effective color (e.g. a fullscreen window whose border is always 0)
        // no longer fire a redundant attribute update.
        if (s.border_cache.get(win)) |cached| {
            if (cached == color) continue;
        }
        _ = xcb.xcb_change_window_attributes(wm.conn, win, xcb.XCB_CW_BORDER_PIXEL, &[_]u32{color});
        s.border_cache.put(s.allocator, win, color) catch {};
    }
}

// Window reordering

/// Move the window at `from_idx` to `to_idx` in tiling order.
fn moveWindowToIndex(s: *State, from_idx: usize, to_idx: usize) void {
    if (from_idx == to_idx) return;
    const current = s.windows.items();
    if (current.len == 0) return;

    var temp: [256]u32 = undefined;
    if (current.len > temp.len) {
        debug.warn("moveWindowToIndex: too many windows ({})", .{current.len});
        return;
    }

    const win = current[from_idx];
    var j: usize = 0;
    for (current, 0..) |w, i| {
        if (i == from_idx) continue;
        if (j == to_idx) { temp[j] = win; j += 1; }
        temp[j] = w;
        j += 1;
    }
    if (to_idx >= j) { temp[j] = win; j += 1; }
    s.windows.reorder(temp[0..j]);
}

pub fn swapWithMaster(wm: *WM) void {
    const s = getState() orelse return;
    const focused = wm.focused_window orelse return;
    if (!s.windows.contains(focused) or !workspaces.isOnCurrentWorkspace(focused)) return;

    const all = s.windows.items();
    if (all.len < 2) return;

    const focused_pos = std.mem.indexOfScalar(u32, all, focused) orelse return;

    // Find first window on current workspace — that's the effective master.
    const master_pos = for (all, 0..) |win, i| {
        if (workspaces.isOnCurrentWorkspace(win)) break i;
    } else return;

    if (focused_pos == master_pos) {
        // Already master: swap with the next workspace window.
        for (all[master_pos + 1..], master_pos + 1..) |win, i| {
            if (workspaces.isOnCurrentWorkspace(win)) {
                moveWindowToIndex(s, i, master_pos);
                break;
            }
        }
    } else {
        moveWindowToIndex(s, focused_pos, master_pos);
    }
    // Wrap retile + bar redraw in a single server grab so picom never composites
    // an intermediate frame where only one of the two swapped windows has moved.
    _ = xcb.xcb_grab_server(wm.conn);
    retileCurrentWorkspace(wm);
    bar.redrawImmediate(wm);
    _ = xcb.xcb_ungrab_server(wm.conn);
    utils.flush(wm.conn);
}

// Layout and master controls

pub fn toggleTiling(wm: *WM) void {
    const s = getState() orelse return;
    s.enabled = !s.enabled;
    if (s.enabled) {
        // Wrap retile + bar redraw in a single server grab so picom never
        // composites a frame where windows have snapped to tiled positions
        // but the bar still shows the pre-tiling state.
        _ = xcb.xcb_grab_server(wm.conn);
        retileCurrentWorkspace(wm);
        bar.redrawImmediate(wm);
        _ = xcb.xcb_ungrab_server(wm.conn);
        utils.flush(wm.conn);
    }
    debug.info("Tiling {s}", .{if (s.enabled) "enabled" else "disabled"});
}

/// Synchronize the active layout in tiling state from a workspace's saved layout.
/// Called by workspaces.executeSwitch before retiling so the layout algorithm
/// and bar segment always reflect the incoming workspace's layout.
pub fn syncLayoutFromWorkspace(layout: Layout) void {
    const s = getState() orelse return;
    if (s.layout == layout) return;
    s.layout = layout;
    s.dirty = true; // invalidate geom cache so the correct layout reruns
}

/// Save the current layout to the active workspace (per-workspace mode only).
fn saveLayoutToCurrentWorkspace(layout: Layout) void {
    if (workspaces.getCurrentWorkspaceObject()) |ws| ws.layout = layout;
}

fn applyLayout(wm: *WM, s: *State, layout: Layout) void {
    s.layout = layout;
    if (!wm.config.tiling.global_layout) saveLayoutToCurrentWorkspace(layout);
    // Wrap the retile and bar redraw in a single server grab so the compositor
    // never composites a frame where windows have moved to the new layout
    // positions but the bar still shows the old layout indicator (or vice-versa).
    _ = xcb.xcb_grab_server(wm.conn);
    retileCurrentWorkspace(wm);
    bar.redrawImmediate(wm);
    _ = xcb.xcb_ungrab_server(wm.conn);
    utils.flush(wm.conn);
    debug.info("Layout: {s}", .{@tagName(layout)});
}

pub fn toggleLayout(wm: *WM) void {
    const s = getState() orelse return;
    applyLayout(wm, s, stepCycle(s.layout, true));
}

pub fn toggleLayoutReverse(wm: *WM) void {
    const s = getState() orelse return;
    applyLayout(wm, s, stepCycle(s.layout, false));
}

pub fn adjustMasterCount(wm: *WM, delta: i8) void {
    const s = getState() orelse return;
    const new: i16 = @as(i16, s.master_count) + delta;
    if (new < 0) return;
    const clamped: u8 = @intCast(@min(new, 10));
    // Skip retile when the clamped value is identical to the current count
    // (e.g. already at the maximum and increase is requested).
    if (clamped == s.master_count) return;
    s.master_count = clamped;
    // Wrap retile + bar redraw in a single server grab so the compositor never
    // composites a frame where the master region has resized but the bar still
    // shows the old master count.
    _ = xcb.xcb_grab_server(wm.conn);
    retileCurrentWorkspace(wm);
    bar.redrawImmediate(wm);
    _ = xcb.xcb_ungrab_server(wm.conn);
    utils.flush(wm.conn);
}

pub inline fn increaseMasterCount(wm: *WM) void { adjustMasterCount(wm,  1); }
pub inline fn decreaseMasterCount(wm: *WM) void { adjustMasterCount(wm, -1); }

pub fn adjustMasterWidth(delta: f32) void {
    const s = getState() orelse return;
    s.master_width = @max(defs.MIN_MASTER_WIDTH, @min(MAX_MASTER_WIDTH, s.master_width + delta));
    // Mark dirty instead of calling retileCurrentWorkspace directly.
    // retileIfDirty in the main event loop runs AFTER all pending events are
    // drained, so the configure_window calls and bar.updateIfDirty are flushed
    // together in one batch.  Calling retileCurrentWorkspace here would queue
    // geometry changes before EnterNotify events (from the previous retile) are
    // processed, causing the bar to redraw against an intermediate focus state
    // and then again against the final state — producing a visible flicker.
    // Deferring also coalesces rapid repeated key presses into a single retile.
    s.dirty = true;
}

pub inline fn increaseMasterWidth() void { adjustMasterWidth( 0.025); }
pub inline fn decreaseMasterWidth() void { adjustMasterWidth(-0.025); }

/// Cycle to the next variation for the currently active layout.
/// Each layout's variation is stored independently, so switching layouts
/// and back preserves each layout's last-used variation.
pub fn cycleLayoutVariation(wm: *WM) void {
    const s = getState() orelse return;
    switch (s.layout) {
        .master => {
            s.layout_variations.master = switch (s.layout_variations.master) {
                .lifo => .fifo,
                .fifo => .lifo,
            };
            debug.info("Master variation: {s}", .{@tagName(s.layout_variations.master)});
        },
        .monocle => {
            s.layout_variations.monocle = switch (s.layout_variations.monocle) {
                .gapless => .gaps,
                .gaps    => .gapless,
            };
            debug.info("Monocle variation: {s}", .{@tagName(s.layout_variations.monocle)});
        },
        .grid => {
            s.layout_variations.grid = switch (s.layout_variations.grid) {
                .rigid   => .relaxed,
                .relaxed => .rigid,
            };
            debug.info("Grid variation: {s}", .{@tagName(s.layout_variations.grid)});
        },
        .fibonacci => {
            debug.info("Fibonacci has no variations", .{});
            return; // Nothing to cycle — skip retile and bar update
        },
    }
    _ = xcb.xcb_grab_server(wm.conn);
    retileCurrentWorkspace(wm);
    // Redraw the bar immediately inside the same server grab so the variation
    // indicator updates atomically with the layout geometry change.  The deferred
    // markDirty+updateIfDirty path would leave the old indicator visible for one
    // compositor frame before the bar catches up.
    bar.redrawImmediate(wm);
    _ = xcb.xcb_ungrab_server(wm.conn);
    utils.flush(wm.conn);
}

/// Return the 3-character variation indicator for the current layout.
/// Used by the bar layout segment to display alongside the layout icon.
pub fn getVariationIndicator(s: *const State) []const u8 {
    return switch (s.layout) {
        .master => switch (s.layout_variations.master) {
            .lifo => "[N]",
            .fifo => "=N=",
        },
        .monocle => switch (s.layout_variations.monocle) {
            .gapless => "<->",
            .gaps    => ">-<",
        },
        .grid => switch (s.layout_variations.grid) {
            .rigid   => "[#]",
            .relaxed => "[~]",
        },
        .fibonacci => &s.fibonacci_indicator,
    };
}

fn filterWorkspaceWindows(s: *State, buf: []u32) usize {
    var n: usize = 0;
    for (s.windows.items()) |win| {
        if (n >= buf.len) break;
        if (workspaces.isOnCurrentWorkspace(win)) { buf[n] = win; n += 1; }
    }
    return n;
}
