//! Tiling window management: delegates to layout modules.

const std        = @import("std");
const defs       = @import("defs");
const xcb        = defs.xcb;
const WM         = defs.WM;
const utils      = @import("utils");
const constants  = @import("constants");
const workspaces = @import("workspaces");
const focus      = @import("focus");
const bar        = @import("bar");
const Tracking   = @import("tracking").Tracking;
const debug      = @import("debug");
const dpi        = @import("dpi");
const layouts    = @import("layouts");

// layout_flags is generated by build.zig after discoverModules runs. It contains
// one `has_X` bool per known layout name, reflecting which files exist on disk.
const layout_flags = @import("layout_flags");

const LayoutStub = struct {
    pub fn tileWithOffset(
        _: *const layouts.LayoutCtx,
        _: anytype,
        _: []const u32,
        _: u16, _: u16, _: u16,
    ) void {}
};

const master_layout    = if (layout_flags.has_master)    @import("master")    else LayoutStub;
const monocle_layout   = if (layout_flags.has_monocle)   @import("monocle")   else LayoutStub;
const grid_layout      = if (layout_flags.has_grid)      @import("grid")      else LayoutStub;
const fibonacci_layout = if (layout_flags.has_fibonacci) @import("fibonacci") else LayoutStub;
const fullscreen = @import("fullscreen");

const MAX_MASTER_WIDTH: f32 = 0.95;
const MAX_WS_WINDOWS: usize = 128;  // stack-local buffer size for per-retile window list
const MAX_WS: usize         = 64;   // matches the u64 ws_geom_valid bitmask width

inline fn wsBit(ws_idx: anytype) u64 { return @as(u64, 1) << @intCast(ws_idx); }

const ZERO_RECT: utils.Rect = .{ .x = 0, .y = 0, .width = 0, .height = 0 };

pub const Layout = enum { master, monocle, grid, fibonacci };

// Layouts present on disk at build time. toggleLayout/toggleLayoutReverse walk
// this list so missing layouts are never visited during cycling.
// A compile error fires if every layout file has been removed.
const LAYOUT_CYCLE: []const Layout = blk: {
    var list: []const Layout = &.{};
    if (layout_flags.has_master)    list = list ++ &[_]Layout{.master};
    if (layout_flags.has_monocle)   list = list ++ &[_]Layout{.monocle};
    if (layout_flags.has_grid)      list = list ++ &[_]Layout{.grid};
    if (layout_flags.has_fibonacci) list = list ++ &[_]Layout{.fibonacci};
    if (list.len == 0) @compileError("No tiling layouts found. Add at least one .zig file to src/tiling/layouts/.");
    break :blk list;
};

pub inline fn defaultLayout() Layout { return LAYOUT_CYCLE[0]; }

fn layoutFromString(name: []const u8) ?Layout {
    if (std.mem.eql(u8, name, "master-stack") or std.mem.eql(u8, name, "master")) return .master;
    if (std.mem.eql(u8, name, "monocle"))    return .monocle;
    if (std.mem.eql(u8, name, "grid"))       return .grid;
    if (std.mem.eql(u8, name, "fibonacci"))  return .fibonacci;
    return null;
}

/// Build the runtime-enabled layout list from the config's `layouts` array,
/// keeping only entries whose .zig file is present on disk. Duplicates are
/// dropped. Falls back to LAYOUT_CYCLE when the config produces an empty list.
fn buildEnabledLayouts(layouts_cfg: []const []const u8) struct { arr: [4]Layout, len: u8 } {
    var arr: [4]Layout = undefined;
    var len: u8 = 0;
    for (layouts_cfg) |name| {
        if (len >= arr.len) break;
        const layout = layoutFromString(name) orelse continue;
        if (!isLayoutAvailable(layout)) continue;
        var seen = false;
        for (arr[0..len]) |l| if (l == layout) { seen = true; break; };
        if (seen) continue;
        arr[len] = layout;
        len += 1;
    }
    if (len == 0) {
        for (LAYOUT_CYCLE) |l| { arr[len] = l; len += 1; }
    }
    return .{ .arr = arr, .len = len };
}

pub inline fn isLayoutAvailable(layout: Layout) bool {
    return switch (layout) {
        .master    => layout_flags.has_master,
        .monocle   => layout_flags.has_monocle,
        .grid      => layout_flags.has_grid,
        .fibonacci => layout_flags.has_fibonacci,
    };
}

// Walk the runtime-enabled layout list to find `current`, then step forward or
// backward. Falls back to LAYOUT_CYCLE if state has no enabled layouts (should
// not happen after init, but guarded defensively).
inline fn stepCycle(s: *const State, current: Layout, comptime forward: bool) Layout {
    const cycle = s.enabled_layouts[0..s.enabled_layouts_len];
    if (cycle.len == 0) {
        for (LAYOUT_CYCLE, 0..) |l, i| {
            if (l == current) return LAYOUT_CYCLE[
                if (forward) (i + 1) % LAYOUT_CYCLE.len
                else         (LAYOUT_CYCLE.len + i - 1) % LAYOUT_CYCLE.len
            ];
        }
        return LAYOUT_CYCLE[0];
    }
    for (cycle, 0..) |l, i| {
        if (l == current) return cycle[
            if (forward) (i + 1) % cycle.len
            else         (cycle.len + i - 1) % cycle.len
        ];
    }
    return cycle[0]; // current not in list (layout disabled at reload) — jump to first
}

// Variation enums are defined in defs.zig to allow config.zig to parse them
// without a circular import. Re-exported here for convenience.
pub const MasterVariation  = defs.MasterVariation;
pub const MonocleVariation = defs.MonocleVariation;
pub const GridVariation    = defs.GridVariation;

pub const LayoutVariations = struct {
    master:  MasterVariation  = .lifo,
    monocle: MonocleVariation = .gapless,
    grid:    GridVariation    = .rigid,
};

pub const State = struct {
    allocator:        std.mem.Allocator,
    enabled:          bool,
    layout:           Layout,
    layout_variations: LayoutVariations,
    /// 3-character indicator shown in the bar for the fibonacci layout.
    fibonacci_indicator: [3]u8,
    master_side:      defs.MasterSide,
    master_width:     f32,
    master_count:     u8,
    gap_width:        u16,
    border_width:     u16,
    border_focused:   u32,
    border_unfocused: u32,
    windows:          Tracking,
    dirty:            bool,

    /// Runtime layout cycle: intersection of config `layouts` and disk-present
    /// layout files. stepCycle walks this so layouts omitted from the config
    /// are invisible at runtime even if their .zig file exists on disk.
    enabled_layouts:     [4]Layout,
    enabled_layouts_len: u8,

    /// Per-workspace geometry validity bitmask (64 bits -> up to 64 workspaces).
    ///
    /// Bit N is set when workspace N's geometry has been pre-computed and the
    /// cache holds correct on-screen positions for all its windows.
    ///
    /// Cleared by: addWindow, removeWindow, adjustMasterWidth, syncLayoutFromWorkspace.
    /// Set by the retile call that immediately follows each of those.
    ws_geom_valid:    u64,

    /// Screen area used in the most recent retile call. restoreWorkspaceGeom
    /// rejects the cache when this differs from the current area (e.g. after a
    /// bar height or position change).
    last_retile_screen: utils.Rect,

    /// Per-window cache storing last geometry AND last border color in a single
    /// hash table. Populated by configureSafe (rect) and sendBorderColor (border).
    cache: layouts.CacheMap,

    pub inline fn margins(self: *const State) utils.Margins {
        return .{ .gap = self.gap_width, .border = self.border_width };
    }

    pub inline fn borderColor(self: *const State, win: u32) u32 {
        if (fullscreen.isFullscreen(win)) return 0;
        return if (focus.getFocused() == win) self.border_focused else self.border_unfocused;
    }

    pub fn deinit(self: *State) void {
        self.windows.deinit();
        self.cache.deinit(self.allocator);
    }
};

// Module singleton -- guaranteed live after init(), never null during normal operation.
// g_initialized guards debug assertions; production builds pay zero cost.
var g_state:       State = undefined;
var g_initialized: bool  = false;

/// Returns a pointer to the live state. Asserts in Debug builds that init() has been called.
pub inline fn getState() *State {
    std.debug.assert(g_initialized);
    return &g_state;
}

/// Safe pre-init query for code that may run before the event loop starts.
/// Returns null only during the narrow startup window before init() is called.
pub inline fn getStateOpt() ?*State {
    return if (g_initialized) &g_state else null;
}

fn computeMasterWidth(wm: *WM) f32 {
    const raw = dpi.scaleMasterWidth(wm.config.tiling.master_width);
    if (raw < 0) {
        const ratio = -raw / @as(f32, @floatFromInt(wm.screen.width_in_pixels));
        return @min(MAX_MASTER_WIDTH, @max(constants.MIN_MASTER_WIDTH, ratio));
    }
    return raw;
}

fn buildState(wm: *WM) State {
    const screen_height = wm.screen.height_in_pixels;
    const el = buildEnabledLayouts(wm.config.tiling.layouts.items);
    return .{
        .allocator        = wm.allocator,
        .enabled          = wm.config.tiling.enabled,
        .layout           = blk: {
            const requested = std.meta.stringToEnum(Layout, wm.config.tiling.layout)
                orelse LAYOUT_CYCLE[0];
            break :blk if (isLayoutAvailable(requested)) requested else LAYOUT_CYCLE[0];
        },
        .enabled_layouts     = el.arr,
        .enabled_layouts_len = el.len,
        .layout_variations = .{
            .master  = wm.config.tiling.master_variation,
            .monocle = wm.config.tiling.monocle_variation,
            .grid    = wm.config.tiling.grid_variation,
        },
        .fibonacci_indicator = wm.config.tiling.fibonacci_indicator,
        .master_side      = wm.config.tiling.master_side,
        .master_width     = computeMasterWidth(wm),
        .master_count     = wm.config.tiling.master_count,
        .gap_width        = dpi.scaleGaps(wm.config.tiling.gap_width, wm.dpi_info.scale_factor, screen_height),
        .border_width     = dpi.scaleBorderWidth(wm.config.tiling.border_width, wm.dpi_info.scale_factor, screen_height),
        .border_focused   = wm.config.tiling.border_focused,
        .border_unfocused = wm.config.tiling.border_unfocused,
        .windows          = Tracking.init(wm.allocator),
        .dirty            = false,
        .ws_geom_valid    = 0,
        .last_retile_screen = ZERO_RECT,
        .cache            = .{},
    };
}

pub fn init(wm: *WM) !void {
    g_state       = buildState(wm);
    g_initialized = true;
}

pub fn deinit() void {
    if (!g_initialized) return;
    g_state.deinit();
    g_initialized = false;
}

pub fn reloadConfig(wm: *WM) void {
    const s = getState();

    const saved_windows = s.windows;

    // Clear the combined cache in-place, retaining the allocated capacity so
    // the next retile does not pay for a fresh heap allocation. The old data
    // is intentionally discarded: config changes (gaps, border width, colors)
    // make every cached rect and border color stale.
    var saved_cache = s.cache;
    saved_cache.clearRetainingCapacity();
    // Disown before buildState overwrites g_state; s is a dangling pointer
    // from this point forward and must not be used.
    s.cache = .{};

    g_state = buildState(wm);
    const ns = &g_state;
    ns.windows = saved_windows;
    ns.cache   = saved_cache;

    // Reset all workspace layouts and master widths to the new config defaults
    // on reload. Per-workspace adjustments made at runtime are intentionally
    // discarded so the reloaded config values take effect immediately.
    if (workspaces.getState()) |ws_state| {
        for (ws_state.workspaces) |*ws| {
            ws.layout       = ns.layout;
            ws.master_width = null;
        }
    }

    if (ns.enabled) {
        // Wrap border-width push and retile in a single server grab so picom
        // never composites an intermediate frame where some windows have the
        // new border width but the layout has not yet been recalculated.
        _ = xcb.xcb_grab_server(wm.conn);
        for (ns.windows.items()) |win| {
            _ = xcb.xcb_configure_window(wm.conn, win,
                xcb.XCB_CONFIG_WINDOW_BORDER_WIDTH, &[_]u32{ns.border_width});
        }
        retileCurrentWorkspace(wm);
        bar.redrawInsideGrab(wm);
        _ = xcb.xcb_ungrab_server(wm.conn);
        _ = xcb.xcb_flush(wm.conn);
    }
}

/// Cache WM_NORMAL_HINTS minimum size constraints for `win`.
/// Called from window.zig at MapRequest time.
pub fn cacheSizeHints(allocator: std.mem.Allocator, win: u32, hints: layouts.SizeHints) void {
    layouts.cacheSizeHints(allocator, win, hints);
}

/// Evict the size-hint entry for `win`. Called from window.zig at unmanage time.
pub fn evictSizeHints(win: u32) void {
    layouts.evictSizeHints(win);
}

pub fn addWindow(wm: *WM, window_id: u32) void {
    std.debug.assert(window_id != 0);
    const s = getState();
    if (!s.enabled) return;

    const result = if (s.layout == .master and s.layout_variations.master == .fifo)
        s.windows.addFront(window_id)
    else
        s.windows.add(window_id);
    result catch |err| { debug.logError(err, window_id); return; };
    s.dirty = true;
    s.ws_geom_valid = 0;

    const border_color = s.borderColor(window_id);
    _ = xcb.xcb_change_window_attributes(wm.conn, window_id,
        xcb.XCB_CW_BORDER_PIXEL, &[_]u32{border_color});
    _ = xcb.xcb_configure_window(wm.conn, window_id,
        xcb.XCB_CONFIG_WINDOW_BORDER_WIDTH, &[_]u32{s.border_width});

    // Pre-populate the cache so the immediately-following retile does not
    // re-send the border pixel.
    const gop = s.cache.getOrPut(s.allocator, window_id) catch return;
    gop.value_ptr.border = border_color;
    if (!gop.found_existing) gop.value_ptr.rect = ZERO_RECT;
}

pub fn removeWindow(window_id: u32) void {
    const s = getState();
    if (s.windows.remove(window_id)) {
        s.dirty = true;
        s.ws_geom_valid = 0;
        _ = s.cache.remove(window_id);
    }
}

/// Toggle a window between tiled and floating.
///
/// Tiled -> floating: removes from the tiling pool so it sits at its current position.
/// Floating -> tiled: hands back to the tiling pool (respecting LIFO/FIFO) and retiles.
pub fn toggleWindowFloat(wm: *WM, window_id: u32) void {
    const s = getState();
    if (!s.enabled) return;

    if (s.windows.contains(window_id)) {
        removeWindow(window_id);
        debug.info("[FLOAT] 0x{x} -> floating", .{window_id});
    } else {
        addWindow(wm, window_id);
        debug.info("[FLOAT] 0x{x} -> tiled", .{window_id});
    }
    retileCurrentWorkspace(wm);
    _ = xcb.xcb_flush(wm.conn);
}

/// Save geometry for any window (tiled or floating) into the shared cache.
/// Called by the workspace switcher before pushing windows off-screen so that
/// floating windows can be restored to their exact position on return.
pub fn saveWindowGeom(window_id: u32, rect: utils.Rect) void {
    const s = getState();
    const gop = s.cache.getOrPut(s.allocator, window_id) catch return;
    gop.value_ptr.rect = rect;
    if (!gop.found_existing) gop.value_ptr.border = 0;
}

/// Return the cached geometry for any window. Returns null when no entry exists
/// or the entry has been invalidated (zeroed rect).
pub inline fn getWindowGeom(window_id: u32) ?utils.Rect {
    const s = getStateOpt() orelse return null;
    const wd = s.cache.get(window_id) orelse return null;
    if (wd.rect.width == 0 and wd.rect.height == 0) return null;
    return wd.rect;
}

// Evict a window's rect from the cache without removing it from tiling.
// Call whenever a window's position is changed outside the normal retile path
// (e.g. pushed offscreen during fullscreen) so the next retile does not find a
// stale cache hit and skip configure_window. The border entry is preserved.
pub fn invalidateGeomCache(window_id: u32) void {
    const s = getState();
    if (s.cache.getPtr(window_id)) |wd| wd.rect = ZERO_RECT;
}

/// Clear the workspace-valid bit for `ws_idx` so the next restoreWorkspaceGeom
/// for that workspace triggers a full retile. Used when a window's tag changes
/// for an inactive workspace without touching the current one.
pub inline fn invalidateWsGeomBit(ws_idx: u8) void {
    const s = getState();
    if (ws_idx < MAX_WS) s.ws_geom_valid &= ~wsBit(ws_idx);
}

pub inline fn dirty() void {
    getState().dirty = true;
}

// Restore windows on the current workspace to their cached tiled positions,
// bypassing the layout algorithm.
// Returns true if the cache is valid and positions have been replayed.
// Returns false if the cache is stale; caller must fall back to retileCurrentWorkspace.
pub fn restoreWorkspaceGeom(wm: *WM) bool {
    const s = getStateOpt() orelse return false;

    var ws_buf: [MAX_WS_WINDOWS]u32 = undefined;
    const ws_count = filterWorkspaceWindows(s, &ws_buf, null);
    const ws_windows = ws_buf[0..ws_count];
    if (ws_windows.len == 0) return true;

    const current_ws = workspaces.getCurrentWorkspace() orelse return false;
    if (current_ws >= MAX_WS) return false;
    if (s.ws_geom_valid & wsBit(current_ws) == 0) return false;

    const current_screen = calculateScreenArea(wm);
    if (!layouts.rectsEqual(current_screen, s.last_retile_screen)) return false;

    // Verify every window is cached before emitting any XCB calls.
    var rects: [MAX_WS_WINDOWS]utils.Rect = undefined;
    for (ws_windows, 0..) |win, i| {
        const wd = s.cache.get(win) orelse return false;
        if (wd.rect.width == 0 and wd.rect.height == 0) return false; // stale entry
        rects[i] = wd.rect;
    }

    for (ws_windows, rects[0..ws_windows.len]) |win, rect| {
        utils.configureWindow(wm.conn, win, rect);
    }
    updateBorders(s, wm, ws_windows);
    return true;
}

pub inline fn isWindowTiled(window_id: u32) bool {
    const s = getStateOpt() orelse return false;
    return s.windows.contains(window_id);
}

/// Returns true only when tiling is *actively running* (runtime toggle on) AND
/// the window is managed by the tiler. Use this in handleConfigureRequest instead
/// of `wm.config.tiling.enabled and isWindowTiled(win)` so that toggling tiling
/// off at runtime actually frees applications to reposition themselves.
pub inline fn isWindowActiveTiled(window_id: u32) bool {
    const s = getStateOpt() orelse return false;
    return s.enabled and s.windows.contains(window_id);
}

fn resolveLayout(s: *State, ws_state: ?*workspaces.State, ws_idx: u8, global: bool) Layout {
    if (global) return s.layout;
    const wss = ws_state orelse return s.layout;
    return if (ws_idx < wss.workspaces.len) wss.workspaces[ws_idx].layout else s.layout;
}

inline fn makeLayoutCtx(s: *State, wm: *WM) layouts.LayoutCtx {
    return .{ .conn = wm.conn, .cache = &s.cache, .allocator = s.allocator };
}

fn dispatchLayout(layout: Layout, ctx: *const layouts.LayoutCtx, s: *State, wins: []const u32, screen: utils.Rect) void {
    const w = screen.width;
    const h = screen.height;
    const y: u16 = @intCast(screen.y);
    switch (layout) {
        .master    => master_layout.tileWithOffset(ctx, s, wins, w, h, y),
        .monocle   => monocle_layout.tileWithOffset(ctx, s, wins, w, h, y),
        .grid      => grid_layout.tileWithOffset(ctx, s, wins, w, h, y),
        .fibonacci => fibonacci_layout.tileWithOffset(ctx, s, wins, w, h, y),
    }
}

inline fn calculateScreenArea(wm: *WM) utils.Rect {
    const bar_height: u16 = if (bar.isVisible()) bar.getBarHeight() else 0;
    const bar_at_bottom   = wm.config.bar.vertical_position == .bottom;
    return .{
        .x      = 0,
        .y      = if (bar_at_bottom) 0 else @intCast(bar_height),
        .width  = wm.screen.width_in_pixels,
        .height = wm.screen.height_in_pixels -| bar_height,
    };
}

pub fn retileAllWorkspaces(wm: *WM) void {
    const s = getState();
    if (!s.enabled) return;

    const screen     = calculateScreenArea(wm);
    const ws_count   = workspaces.getWorkspaceCount();
    const current_ws = workspaces.getCurrentWorkspace() orelse return;

    const ws_state_opt = if (!wm.config.tiling.global_layout) workspaces.getState() else null;

    const ctx          = makeLayoutCtx(s, wm);
    const effective_ws = @min(ws_count, MAX_WS);
    var bufs: [MAX_WS][MAX_WS_WINDOWS]u32 = undefined;
    var lens: [MAX_WS]usize               = @splat(0);

    for (s.windows.items()) |win| {
        const ws_idx = workspaces.getWorkspaceForWindow(win) orelse continue;
        if (ws_idx >= effective_ws) continue;
        if (lens[ws_idx] < MAX_WS_WINDOWS) {
            bufs[ws_idx][lens[ws_idx]] = win;
            lens[ws_idx] += 1;
        }
    }

    var ws_idx: u8 = 0;
    while (ws_idx < effective_ws) : (ws_idx += 1) {
        if (ws_idx == current_ws) continue;
        if (fullscreen.getForWorkspace(ws_idx)) |_| continue;

        const ws_windows = bufs[ws_idx][0..lens[ws_idx]];
        if (ws_windows.len == 0) continue;

        dispatchLayout(resolveLayout(s, ws_state_opt, ws_idx, wm.config.tiling.global_layout), &ctx, s, ws_windows, screen);
        updateBorders(s, wm, ws_windows);
        markWsGeomValid(s, ws_idx);
    }

    s.last_retile_screen = screen;
}

pub fn retileIfDirty(wm: *WM) void {
    const s = getState();
    if (!s.enabled or !s.dirty) return;
    retileCurrentWorkspace(wm);
}

pub fn retileCurrentWorkspace(wm: *WM) void {
    const s = getState();
    if (!s.enabled) return;
    retile(wm, calculateScreenArea(wm), null);
    s.dirty = false;
}

/// Retile a specific inactive workspace so its geometry cache is correct before
/// the user switches to it.
///
/// MUST be called inside a server grab: retile transiently moves windows to
/// their on-screen positions.
pub fn retileInactiveWorkspace(wm: *WM, ws_idx: u8) void {
    const s = getState();
    if (!s.enabled) return;

    const ws_state = workspaces.getState() orelse return;

    if (ws_idx == ws_state.current) {
        retileCurrentWorkspace(wm);
        return;
    }

    retile(wm, calculateScreenArea(wm), ws_idx);

    // Push windows back offscreen while their workspace is inactive.
    // Do NOT invalidate the cache: restoreWorkspaceGeom will find the
    // ws_geom_valid bit set, a complete cache, and a matching screen rect,
    // and replay positions in one batch.
    for (ws_state.workspaces[ws_idx].windows.items()) |win| {
        _ = xcb.xcb_configure_window(wm.conn, win,
            xcb.XCB_CONFIG_WINDOW_X,
            &[_]u32{@bitCast(@as(i32, constants.OFFSCREEN_X_POSITION))});
    }
}

// Core retile. `for_ws`: when non-null, process that specific workspace instead
// of the current one.
fn retile(wm: *WM, screen: utils.Rect, for_ws: ?u8) void {
    const s = getState();

    const target_ws: u8 = for_ws orelse
        @intCast(workspaces.getCurrentWorkspace() orelse return);

    if (fullscreen.getForWorkspace(target_ws)) |_| return;

    var ws_buf: [MAX_WS_WINDOWS]u32 = undefined;
    const ws_count = filterWorkspaceWindows(s, &ws_buf, for_ws);
    const ws_windows = ws_buf[0..ws_count];
    if (ws_windows.len == 0) return;

    const ctx = makeLayoutCtx(s, wm);
    dispatchLayout(resolveLayout(s, workspaces.getState(), target_ws, wm.config.tiling.global_layout), &ctx, s, ws_windows, screen);

    s.last_retile_screen = screen;
    updateBorders(s, wm, ws_windows);
    markWsGeomValid(s, target_ws);
}

// Send border pixel only if color changed since last send.
fn sendBorderColor(s: *State, conn: *xcb.xcb_connection_t, win: u32, color: u32) void {
    const gop = s.cache.getOrPut(s.allocator, win) catch {
        _ = xcb.xcb_change_window_attributes(conn, win, xcb.XCB_CW_BORDER_PIXEL, &[_]u32{color});
        return;
    };
    if (gop.found_existing and gop.value_ptr.border == color) return;
    gop.value_ptr.border = color;
    if (!gop.found_existing) gop.value_ptr.rect = ZERO_RECT;
    _ = xcb.xcb_change_window_attributes(conn, win, xcb.XCB_CW_BORDER_PIXEL, &[_]u32{color});
}

inline fn updateBorders(s: *State, wm: *WM, ws_windows: []const u32) void {
    for (ws_windows) |win| sendBorderColor(s, wm.conn, win, s.borderColor(win));
}

pub fn updateWindowFocus(wm: *WM, old_focused: ?u32, new_focused: ?u32) void {
    const s = getState();
    for ([2]?u32{ old_focused, new_focused }) |opt| {
        const win = opt orelse continue;
        if (!s.windows.contains(win)) continue;
        sendBorderColor(s, wm.conn, win, s.borderColor(win));
    }
}

fn moveWindowToIndex(s: *State, from_idx: usize, to_idx: usize) void {
    if (from_idx == to_idx) return;
    const current = s.windows.items();

    var temp: [MAX_WS_WINDOWS]u32 = undefined;
    if (current.len > temp.len) {
        debug.warn("moveWindowToIndex: too many windows ({})", .{current.len});
        return;
    }

    const win = current[from_idx];
    var j: usize = 0;
    for (current, 0..) |w, i| {
        if (i == from_idx) continue;
        if (j == to_idx) { temp[j] = win; j += 1; }
        temp[j] = w;
        j += 1;
    }
    if (to_idx >= j) { temp[j] = win; j += 1; }
    s.windows.reorder(temp[0..j]);
}

pub fn swapWithMaster(wm: *WM) void {
    const s = getState();
    const focused = focus.getFocused() orelse return;
    if (!s.windows.contains(focused) or !workspaces.isOnCurrentWorkspace(focused)) return;

    const all = s.windows.items();
    if (all.len < 2) return;

    var focused_pos: ?usize = null;
    var master_pos:  ?usize = null;
    for (all, 0..) |win, i| {
        if (win == focused) focused_pos = i;
        if (master_pos == null and workspaces.isOnCurrentWorkspace(win)) master_pos = i;
        if (focused_pos != null and master_pos != null) break;
    }
    const fp = focused_pos orelse return;
    const mp = master_pos  orelse return;

    if (fp == mp) {
        for (all[mp + 1..], mp + 1..) |win, i| {
            if (workspaces.isOnCurrentWorkspace(win)) {
                moveWindowToIndex(s, i, mp);
                break;
            }
        }
    } else {
        moveWindowToIndex(s, fp, mp);
    }
    retileCurrentWorkspace(wm);
}

/// Like swapWithMaster, but focus transfers to the displaced window rather than
/// staying on the window that was moved.
pub fn swapWithMasterFocusSwap(wm: *WM) void {
    const s = getState();
    const focused = focus.getFocused() orelse return;
    if (!s.windows.contains(focused) or !workspaces.isOnCurrentWorkspace(focused)) return;

    const all = s.windows.items();
    if (all.len < 2) return;

    var focused_pos: ?usize = null;
    var master_pos:  ?usize = null;
    for (all, 0..) |win, i| {
        if (win == focused) focused_pos = i;
        if (master_pos == null and workspaces.isOnCurrentWorkspace(win)) master_pos = i;
        if (focused_pos != null and master_pos != null) break;
    }
    const fp = focused_pos orelse return;
    const mp = master_pos  orelse return;

    var other_win: ?u32 = null;
    if (fp == mp) {
        // Focused is already master -- swap with next window; focus follows to it.
        for (all[mp + 1..], mp + 1..) |win, i| {
            if (workspaces.isOnCurrentWorkspace(win)) {
                other_win = win;
                moveWindowToIndex(s, i, mp);
                break;
            }
        }
    } else {
        // Focused is a slave -- swap into master; focus follows to the old master.
        other_win = all[mp];
        moveWindowToIndex(s, fp, mp);
    }
    retileCurrentWorkspace(wm);
    if (other_win) |win| focus.setFocus(wm, win, .tiling_operation);
}

pub fn toggleTiling(wm: *WM) void {
    const s = getState();
    s.enabled = !s.enabled;
    if (s.enabled) retileCurrentWorkspace(wm);
    debug.info("Tiling {s}", .{if (s.enabled) "enabled" else "disabled"});
}

pub fn syncLayoutFromWorkspace(ws: *const workspaces.Workspace) void {
    const s = getState();
    const layout = ws.layout;
    const needs_retile = s.layout != layout or ws.variation != null;
    s.layout = layout;
    // Apply the workspace-pinned master width when present; fall back to the
    // current global value so unvisited workspaces inherit the config default.
    if (ws.master_width) |mw| s.master_width = mw;
    // Apply the workspace-pinned variation override when present. A null
    // variation means "use the global default", so leave layout_variations alone.
    if (ws.variation) |v| {
        switch (v) {
            .master    => |mv| s.layout_variations.master  = mv,
            .monocle   => |mv| s.layout_variations.monocle = mv,
            .grid      => |gv| s.layout_variations.grid    = gv,
            .fibonacci => {},
        }
    }
    if (needs_retile) {
        s.dirty = true;
        s.ws_geom_valid = 0;
    }
}

fn applyLayout(wm: *WM, s: *State, layout: Layout) void {
    s.layout = layout;
    if (!wm.config.tiling.global_layout)
        if (workspaces.getCurrentWorkspaceObject()) |ws| { ws.layout = layout; };
    retileCurrentWorkspace(wm);
    debug.info("Layout: {s}", .{@tagName(layout)});
}

pub fn toggleLayout(wm: *WM) void {
    const s = getState();
    applyLayout(wm, s, stepCycle(s, s.layout, true));
}

pub fn toggleLayoutReverse(wm: *WM) void {
    const s = getState();
    applyLayout(wm, s, stepCycle(s, s.layout, false));
}

pub fn adjustMasterCount(wm: *WM, delta: i8) void {
    const s = getState();
    const new: i16 = @as(i16, s.master_count) + delta;
    if (new < 0) return;
    const clamped: u8 = @intCast(@min(new, 10));
    if (clamped == s.master_count) return;
    s.master_count = clamped;
    retileCurrentWorkspace(wm);
}

pub inline fn increaseMasterCount(wm: *WM) void { adjustMasterCount(wm,  1); }
pub inline fn decreaseMasterCount(wm: *WM) void { adjustMasterCount(wm, -1); }

pub fn adjustMasterWidth(wm: *WM, delta: f32) void {
    const s = getState();
    s.master_width = @max(constants.MIN_MASTER_WIDTH, @min(MAX_MASTER_WIDTH, s.master_width + delta));
    // In per-workspace layout mode, persist the new width onto the current
    // workspace so it is restored when switching back to this workspace.
    if (!wm.config.tiling.global_layout) {
        if (workspaces.getCurrentWorkspaceObject()) |ws| ws.master_width = s.master_width;
    }
    s.dirty = true;
    s.ws_geom_valid = 0;
    retileCurrentWorkspace(wm);
}

pub inline fn increaseMasterWidth(wm: *WM) void { adjustMasterWidth(wm,  0.025); }
pub inline fn decreaseMasterWidth(wm: *WM) void { adjustMasterWidth(wm, -0.025); }

pub fn cycleLayoutVariation(wm: *WM) void {
    const s = getState();
    switch (s.layout) {
        .master => {
            s.layout_variations.master = switch (s.layout_variations.master) {
                .lifo => .fifo,
                .fifo => .lifo,
            };
            debug.info("Master variation: {s}", .{@tagName(s.layout_variations.master)});
        },
        .monocle => {
            s.layout_variations.monocle = switch (s.layout_variations.monocle) {
                .gapless => .gaps,
                .gaps    => .gapless,
            };
            debug.info("Monocle variation: {s}", .{@tagName(s.layout_variations.monocle)});
        },
        .grid => {
            s.layout_variations.grid = switch (s.layout_variations.grid) {
                .rigid   => .relaxed,
                .relaxed => .rigid,
            };
            debug.info("Grid variation: {s}", .{@tagName(s.layout_variations.grid)});
        },
        .fibonacci => {
            debug.info("Fibonacci has no variations", .{});
            return;
        },
    }
    retileCurrentWorkspace(wm);
    bar.scheduleRedraw();
}

inline fn markWsGeomValid(s: *State, ws_idx: anytype) void {
    if (ws_idx < MAX_WS) s.ws_geom_valid |= wsBit(ws_idx);
}

// Collect windows belonging to the target workspace into buf.
// `for_ws`: when non-null, filter by that workspace index; when null, use current.
fn filterWorkspaceWindows(s: *State, buf: []u32, for_ws: ?u8) usize {
    var n: usize = 0;
    for (s.windows.items()) |win| {
        if (n >= buf.len) break;
        const on_ws = if (for_ws) |idx|
            workspaces.isWindowOnWorkspace(win, idx)
        else
            workspaces.isOnCurrentWorkspace(win);
        if (on_ws) { buf[n] = win; n += 1; }
    }
    return n;
}
