//! Tiling window management: delegates to layout modules.

const std        = @import("std");
const defs       = @import("defs");
const xcb        = defs.xcb;
const WM         = defs.WM;
const utils      = @import("utils");
const constants  = @import("constants");
const workspaces = @import("workspaces");
const focus      = @import("focus");
const bar        = @import("bar");
const Tracking   = @import("tracking").Tracking;
const debug      = @import("debug");
const dpi        = @import("dpi");
const layouts    = @import("layouts");

// layout_flags is generated by build.zig after discoverModules runs. It contains
// one `has_X` bool per known layout name, reflecting which files exist on disk.
const layout_flags = @import("layout_flags");

const LayoutStub = struct {
    pub fn tileWithOffset(
        _: *const layouts.LayoutCtx,
        _: anytype,
        _: []const u32,
        _: u16, _: u16, _: u16,
    ) void {}
};

const master_layout    = if (layout_flags.has_master)    @import("master")    else LayoutStub;
const monocle_layout   = if (layout_flags.has_monocle)   @import("monocle")   else LayoutStub;
const grid_layout      = if (layout_flags.has_grid)      @import("grid")      else LayoutStub;
const fibonacci_layout = if (layout_flags.has_fibonacci) @import("fibonacci") else LayoutStub;
const fullscreen = @import("fullscreen");

const MAX_MASTER_WIDTH: f32 = 0.95;
const DEFAULT_MAX_WS_WINDOWS: usize = 128;  // default per-retile window list capacity
const DEFAULT_MAX_WS: usize         = 64;   // default workspace limit; matches u64 ws_geom_valid bitmask

inline fn wsBit(ws_idx: anytype) u64 { return @as(u64, 1) << @intCast(ws_idx); }

const ZERO_RECT: utils.Rect = .{ .x = 0, .y = 0, .width = 0, .height = 0 };

pub const Layout = enum { master, monocle, grid, fibonacci };

// Layouts present on disk at build time. toggleLayout/toggleLayoutReverse walk
// this list so missing layouts are never visited during cycling.
// A compile error fires if every layout file has been removed.
const LAYOUT_CYCLE: []const Layout = blk: {
    var list: []const Layout = &.{};
    if (layout_flags.has_master)    list = list ++ &[_]Layout{.master};
    if (layout_flags.has_monocle)   list = list ++ &[_]Layout{.monocle};
    if (layout_flags.has_grid)      list = list ++ &[_]Layout{.grid};
    if (layout_flags.has_fibonacci) list = list ++ &[_]Layout{.fibonacci};
    if (list.len == 0) @compileError("No tiling layouts found. Add at least one .zig file to src/tiling/layouts/.");
    break :blk list;
};

pub inline fn defaultLayout() Layout { return LAYOUT_CYCLE[0]; }

const LAYOUT_NAME_MAP = std.StaticStringMap(Layout).initComptime(.{
    .{ "master-stack", .master }, .{ "master", .master },
    .{ "monocle",      .monocle },
    .{ "grid",         .grid    },
    .{ "fibonacci",    .fibonacci },
});

inline fn layoutFromString(name: []const u8) ?Layout { return LAYOUT_NAME_MAP.get(name); }

/// Build the runtime-enabled layout list from the config's `layouts` array,
/// keeping only entries whose .zig file is present on disk. Duplicates are
/// dropped. Falls back to LAYOUT_CYCLE when the config produces an empty list.
fn buildEnabledLayouts(layouts_cfg: []const []const u8) struct { arr: [4]Layout, len: u8 } {
    var arr: [4]Layout = undefined;
    var len: u8 = 0;
    for (layouts_cfg) |name| {
        if (len >= arr.len) break;
        const layout = layoutFromString(name) orelse continue;
        if (!isLayoutAvailable(layout)) continue;
        if (std.mem.indexOfScalar(Layout, arr[0..len], layout) != null) continue;
        arr[len] = layout;
        len += 1;
    }
    if (len == 0) {
        for (LAYOUT_CYCLE) |l| { arr[len] = l; len += 1; }
    }
    return .{ .arr = arr, .len = len };
}

pub inline fn isLayoutAvailable(layout: Layout) bool {
    return switch (layout) {
        .master    => layout_flags.has_master,
        .monocle   => layout_flags.has_monocle,
        .grid      => layout_flags.has_grid,
        .fibonacci => layout_flags.has_fibonacci,
    };
}

// Walk the runtime-enabled layout list to find `current`, then step forward or
// backward. Falls back to LAYOUT_CYCLE if state has no enabled layouts (should
// not happen after init, but guarded defensively).
inline fn stepCycle(s: *const State, current: Layout, comptime forward: bool) Layout {
    const cycle: []const Layout = if (s.enabled_layouts_len > 0)
        s.enabled_layouts[0..s.enabled_layouts_len]
    else
        LAYOUT_CYCLE;
    for (cycle, 0..) |l, i| {
        if (l != current) continue;
        return cycle[if (forward) (i + 1) % cycle.len else (cycle.len + i - 1) % cycle.len];
    }
    return cycle[0]; // current not in list (layout disabled at reload) — jump to first
}

// Variation enums are defined in defs.zig to allow config.zig to parse them
// without a circular import. Re-exported here for convenience.
pub const MasterVariation  = defs.MasterVariation;
pub const MonocleVariation = defs.MonocleVariation;
pub const GridVariation    = defs.GridVariation;

pub const LayoutVariations = struct {
    master:  MasterVariation  = .lifo,
    monocle: MonocleVariation = .gapless,
    grid:    GridVariation    = .rigid,
};

pub const State = struct {
    allocator:        std.mem.Allocator,
    enabled:          bool,
    layout:           Layout,
    layout_variations: LayoutVariations,
    /// 3-character indicator shown in the bar for the fibonacci layout.
    fibonacci_indicator: [3]u8,
    master_side:      defs.MasterSide,
    master_width:     f32,
    master_count:     u8,
    gap_width:        u16,
    border_width:     u16,
    border_focused:   u32,
    border_unfocused: u32,
    windows:          Tracking,
    dirty:            bool,

    /// Runtime layout cycle: intersection of config `layouts` and disk-present
    /// layout files. stepCycle walks this so layouts omitted from the config
    /// are invisible at runtime even if their .zig file exists on disk.
    enabled_layouts:     [4]Layout,
    enabled_layouts_len: u8,

    /// Per-workspace geometry validity bitmask (64 bits -> up to 64 workspaces).
    ///
    /// Bit N is set when workspace N's geometry has been pre-computed and the
    /// cache holds correct on-screen positions for all its windows.
    ///
    /// Cleared by: addWindow, removeWindow, adjustMasterWidth, syncLayoutFromWorkspace.
    /// Set by the retile call that immediately follows each of those.
    ws_geom_valid:    u64,

    /// Screen area used in the most recent retile call. restoreWorkspaceGeom
    /// rejects the cache when this differs from the current area (e.g. after a
    /// bar height or position change).
    last_retile_screen: utils.Rect,

    /// Per-window cache storing last geometry AND last border color in a single
    /// hash table. Populated by configureSafe (rect) and sendBorderColor (border).
    cache: layouts.CacheMap,

    // Scratch buffers (heap-allocated, sized from max_ws_windows / max_ws) 
    //
    // Reused across retile calls to avoid per-call stack pressure.  All four
    // slices are allocated in buildState and freed in deinit.
    //
    //   scratch_wins   — [max_ws_windows]u32   single-workspace window list
    //   scratch_rects  — [max_ws_windows]Rect  parallel rect array for restore path
    //   retile_wins    — [max_ws * max_ws_windows]u32  flattened 2-D per-workspace lists
    //   retile_lens    — [max_ws]usize          fill counters for retile_wins rows

    max_ws_windows: usize,
    max_ws:         usize,
    scratch_wins:   []u32,
    scratch_rects:  []utils.Rect,
    retile_wins:    []u32,
    retile_lens:    []usize,

    pub inline fn margins(self: *const State) utils.Margins {
        return .{ .gap = self.gap_width, .border = self.border_width };
    }

    pub inline fn borderColor(self: *const State, win: u32) u32 {
        if (fullscreen.isFullscreen(win)) return 0;
        return if (focus.getFocused() == win) self.border_focused else self.border_unfocused;
    }

    pub fn deinit(self: *State) void {
        self.windows.deinit();
        self.cache.deinit(self.allocator);
        self.allocator.free(self.retile_lens);
        self.allocator.free(self.retile_wins);
        self.allocator.free(self.scratch_rects);
        self.allocator.free(self.scratch_wins);
    }
};

// Module singleton -- guaranteed live after init(), never null during normal operation.
// g_initialized guards debug assertions; production builds pay zero cost.
var g_state:       State = undefined;
var g_initialized: bool  = false;

/// Returns a pointer to the live state. Asserts in Debug builds that init() has been called.
pub inline fn getState() *State {
    std.debug.assert(g_initialized);
    return &g_state;
}

/// Safe pre-init query for code that may run before the event loop starts.
/// Returns null only during the narrow startup window before init() is called.
pub inline fn getStateOpt() ?*State {
    return if (g_initialized) &g_state else null;
}

fn computeMasterWidth(wm: *WM) f32 {
    const raw = dpi.scaleMasterWidth(wm.config.tiling.master_width);
    if (raw < 0) {
        const ratio = -raw / @as(f32, @floatFromInt(wm.screen.width_in_pixels));
        return @min(MAX_MASTER_WIDTH, @max(constants.MIN_MASTER_WIDTH, ratio));
    }
    return raw;
}

fn buildState(wm: *WM) !State {
    const alloc            = wm.allocator;
    const max_ws_windows   = DEFAULT_MAX_WS_WINDOWS;
    const max_ws           = DEFAULT_MAX_WS;
    const screen_height    = wm.screen.height_in_pixels;
    const el               = buildEnabledLayouts(wm.config.tiling.layouts.items);

    const scratch_wins  = try alloc.alloc(u32,         max_ws_windows);
    errdefer alloc.free(scratch_wins);
    const scratch_rects = try alloc.alloc(utils.Rect,  max_ws_windows);
    errdefer alloc.free(scratch_rects);
    const retile_wins   = try alloc.alloc(u32,         max_ws * max_ws_windows);
    errdefer alloc.free(retile_wins);
    const retile_lens   = try alloc.alloc(usize,       max_ws);
    errdefer alloc.free(retile_lens);

    return .{
        .allocator        = alloc,
        .enabled          = wm.config.tiling.enabled,
        .layout           = blk: {
            const requested = std.meta.stringToEnum(Layout, wm.config.tiling.layout)
                orelse LAYOUT_CYCLE[0];
            break :blk if (isLayoutAvailable(requested)) requested else LAYOUT_CYCLE[0];
        },
        .enabled_layouts     = el.arr,
        .enabled_layouts_len = el.len,
        .layout_variations = .{
            .master  = wm.config.tiling.master_variation,
            .monocle = wm.config.tiling.monocle_variation,
            .grid    = wm.config.tiling.grid_variation,
        },
        .fibonacci_indicator = wm.config.tiling.fibonacci_indicator,
        .master_side      = wm.config.tiling.master_side,
        .master_width     = computeMasterWidth(wm),
        .master_count     = wm.config.tiling.master_count,
        .gap_width        = dpi.scaleGaps(wm.config.tiling.gap_width, wm.dpi_info.scale_factor, screen_height),
        .border_width     = dpi.scaleBorderWidth(wm.config.tiling.border_width, wm.dpi_info.scale_factor, screen_height),
        .border_focused   = wm.config.tiling.border_focused,
        .border_unfocused = wm.config.tiling.border_unfocused,
        .windows          = Tracking.init(alloc),
        .dirty            = false,
        .ws_geom_valid    = 0,
        .last_retile_screen = ZERO_RECT,
        .cache            = .{},
        .max_ws_windows   = max_ws_windows,
        .max_ws           = max_ws,
        .scratch_wins     = scratch_wins,
        .scratch_rects    = scratch_rects,
        .retile_wins      = retile_wins,
        .retile_lens      = retile_lens,
    };
}

pub fn init(wm: *WM) !void {
    g_state       = try buildState(wm);
    g_initialized = true;
}

pub fn deinit() void {
    if (!g_initialized) return;
    g_state.deinit();
    g_initialized = false;
}

pub fn reloadConfig(wm: *WM) void {
    const s = getState();

    const saved_windows = s.windows;

    // Clear the combined cache in-place, retaining the allocated capacity so
    // the next retile does not pay for a fresh heap allocation. The old data
    // is intentionally discarded: config changes (gaps, border width, colors)
    // make every cached rect and border color stale.
    var saved_cache = s.cache;
    saved_cache.clearRetainingCapacity();
    // Disown before buildState overwrites g_state; s is a dangling pointer
    // from this point forward and must not be used.
    s.cache = .{};

    // Save scratch buffers: buildState allocates fresh ones, but we reuse the
    // existing allocations (same capacity) to avoid needless churn.
    const saved_scratch_wins  = s.scratch_wins;
    const saved_scratch_rects = s.scratch_rects;
    const saved_retile_wins   = s.retile_wins;
    const saved_retile_lens   = s.retile_lens;

    var new_state = buildState(wm) catch |err| {
        // buildState failed before overwriting g_state — restore what we saved.
        s.cache   = saved_cache;
        s.windows = saved_windows;
        debug.err("tiling: out of memory during reload: {}", .{err});
        return;
    };

    // Free the freshly allocated scratch bufs from new_state (same sizes as
    // the saved ones) and replace them with the saved allocations.
    const alloc = new_state.allocator;
    alloc.free(new_state.retile_lens);
    alloc.free(new_state.retile_wins);
    alloc.free(new_state.scratch_rects);
    alloc.free(new_state.scratch_wins);
    new_state.scratch_wins  = saved_scratch_wins;
    new_state.scratch_rects = saved_scratch_rects;
    new_state.retile_wins   = saved_retile_wins;
    new_state.retile_lens   = saved_retile_lens;
    // Discard the empty Tracking allocated by buildState (no items, no heap).
    new_state.windows = saved_windows;
    new_state.cache   = saved_cache;

    g_state = new_state;
    const ns = &g_state;

    // Reset all workspace layouts and master widths to the new config defaults
    // on reload. Per-workspace adjustments made at runtime are intentionally
    // discarded so the reloaded config values take effect immediately.
    if (workspaces.getState()) |ws_state| {
        for (ws_state.workspaces) |*ws| {
            ws.layout       = ns.layout;
            ws.master_width = null;
        }
    }

    if (ns.enabled) {
        // Wrap border-width push and retile in a single server grab so picom
        // never composites an intermediate frame where some windows have the
        // new border width but the layout has not yet been recalculated.
        _ = xcb.xcb_grab_server(wm.conn);
        for (ns.windows.items()) |win| {
            _ = xcb.xcb_configure_window(wm.conn, win,
                xcb.XCB_CONFIG_WINDOW_BORDER_WIDTH, &[_]u32{ns.border_width});
        }
        retileCurrentWorkspace(wm);
        bar.redrawInsideGrab(wm);
        _ = xcb.xcb_ungrab_server(wm.conn);
        _ = xcb.xcb_flush(wm.conn);
    }
}

/// Cache WM_NORMAL_HINTS minimum size constraints for `win`. Called from window.zig at MapRequest time.
pub const cacheSizeHints = layouts.cacheSizeHints;
/// Evict the size-hint entry for `win`. Called from window.zig at unmanage time.
pub const evictSizeHints = layouts.evictSizeHints;

pub fn addWindow(wm: *WM, window_id: u32) void {
    std.debug.assert(window_id != 0);
    const s = getState();
    if (!s.enabled) return;

    const result = if (s.layout == .master and s.layout_variations.master == .fifo)
        s.windows.addFront(window_id)
    else
        s.windows.add(window_id);
    result catch |err| { debug.logError(err, window_id); return; };
    s.dirty = true;
    s.ws_geom_valid = 0;

    const border_color = s.borderColor(window_id);
    _ = xcb.xcb_change_window_attributes(wm.conn, window_id,
        xcb.XCB_CW_BORDER_PIXEL, &[_]u32{border_color});
    _ = xcb.xcb_configure_window(wm.conn, window_id,
        xcb.XCB_CONFIG_WINDOW_BORDER_WIDTH, &[_]u32{s.border_width});

    // Pre-populate the cache so the immediately-following retile does not
    // re-send the border pixel.
    const gop = s.cache.getOrPut(s.allocator, window_id) catch return;
    gop.value_ptr.border = border_color;
    if (!gop.found_existing) gop.value_ptr.rect = ZERO_RECT;
}

pub fn removeWindow(window_id: u32) void {
    const s = getState();
    if (s.windows.remove(window_id)) {
        s.dirty = true;
        s.ws_geom_valid = 0;
        _ = s.cache.remove(window_id);
    }
}

/// Returns the position of `win` in the current-workspace-filtered window
/// list — the same slice the master layout receives as its `windows` argument.
/// Index 0 is the master slot; indices >= master_count are stack slots.
///
/// Must be called BEFORE removeWindow so the window is still tracked.
/// Returns null when tiling is disabled or `win` is not in the tiling list.
pub fn getWindowFilteredIndex(win: u32) ?usize {
    const s = getStateOpt() orelse return null;
    if (!s.enabled) return null;
    var filtered_idx: usize = 0;
    for (s.windows.items()) |w| {
        if (w == win) return filtered_idx;
        if (workspaces.isOnCurrentWorkspace(w)) filtered_idx += 1;
    }
    return null;
}

/// Add `win` to the tiling list and place it at workspace-filtered position
/// `target_filtered_idx`.  If `target_filtered_idx` exceeds the current
/// filtered length the window is left at the back (natural addWindow position).
///
/// Used by the unminimize path to restore a window to its original layout
/// slot.  The index is captured by minimizeWindow via getWindowFilteredIndex
/// before the window is removed.
///
/// Works correctly for both LIFO (default, addWindow appends to end) and
/// FIFO (addFront prepends to front) layout variations.
pub fn addWindowAtFilteredIndex(wm: *WM, win: u32, target_filtered_idx: usize) void {
    addWindow(wm, win);
    moveWindowToFilteredSlot(getState(), win, target_filtered_idx);
}

/// Reposition `win` within the global window list so that it lands at
/// workspace-filtered index `target` (0 = master slot).
///
/// Background — the shift arithmetic:
///   moveWindowToIndex(from, to) removes the source element first, then
///   inserts it at position `to` in the *shortened* list.  When `from` lies
///   before `to` in the original list, the removal shifts every subsequent
///   element left by one, so the effective insertion point is `tg - 1`.
///   When `from` lies after `to` no shift occurs.
///
/// Example (global list [A B C D], workspace = all, target = 1 = "B's slot"):
///   addWindow appended win W → [A B C D W], from_global = 4
///   target window at filtered[1] = B → to_global = 1
///   from(4) > to(1) → effective_to = 1, no shift
///   moveWindowToIndex(4, 1) → [A W B C D]  ✓  filtered[1] = W
///
/// Example (FIFO: addFront prepended W → [W A B C D], from_global = 0):
///   target window at filtered[1] = B → to_global = 2
///   from(0) < to(2) → effective_to = 2 - 1 = 1
///   moveWindowToIndex(0, 1) → [A W B C D]  ✓  filtered[1] = W
fn moveWindowToFilteredSlot(s: *State, win: u32, target: usize) void {
    const items = s.windows.items();

    var from_global: usize = items.len; // sentinel
    for (items, 0..) |w, i| {
        if (w == win) { from_global = i; break; }
    }
    if (from_global == items.len) return; // shouldn't happen

    // Find the global index of the workspace window currently at `target`
    // (excluding win itself).  That window should end up immediately AFTER win,
    // so inserting win just before it places win at the desired filtered slot.
    var filtered_count: usize = 0;
    var to_global: ?usize = null;
    for (items, 0..) |w, i| {
        if (w == win) continue;
        if (!workspaces.isOnCurrentWorkspace(w)) continue;
        if (filtered_count == target) { to_global = i; break; }
        filtered_count += 1;
    }

    const tg = to_global orelse return; // target at/past end — already correct
    const effective_to: usize = if (from_global < tg) tg - 1 else tg;
    if (effective_to != from_global) moveWindowToIndex(s, from_global, effective_to);
}

/// Toggle a window between tiled and floating.
///
/// Tiled -> floating: removes from the tiling pool so it sits at its current position.
/// Floating -> tiled: hands back to the tiling pool (respecting LIFO/FIFO) and retiles.
pub fn toggleWindowFloat(wm: *WM, window_id: u32) void {
    const s = getState();
    if (!s.enabled) return;

    if (s.windows.contains(window_id)) {
        removeWindow(window_id);
        debug.info("[FLOAT] 0x{x} -> floating", .{window_id});
    } else {
        addWindow(wm, window_id);
        debug.info("[FLOAT] 0x{x} -> tiled", .{window_id});
    }
    retileCurrentWorkspace(wm);
    _ = xcb.xcb_flush(wm.conn);
}

/// Save geometry for any window (tiled or floating) into the shared cache.
/// Called by the workspace switcher before pushing windows off-screen so that
/// floating windows can be restored to their exact position on return.
pub fn saveWindowGeom(window_id: u32, rect: utils.Rect) void {
    const s = getState();
    const gop = s.cache.getOrPut(s.allocator, window_id) catch return;
    gop.value_ptr.rect = rect;
    if (!gop.found_existing) gop.value_ptr.border = 0;
}

/// Return the cached geometry for any window. Returns null when no entry exists
/// or the entry has been invalidated (zeroed rect).
pub inline fn getWindowGeom(window_id: u32) ?utils.Rect {
    const s = getStateOpt() orelse return null;
    const wd = s.cache.get(window_id) orelse return null;
    if (wd.rect.width == 0 and wd.rect.height == 0) return null;
    return wd.rect;
}

// Evict a window's rect from the cache without removing it from tiling.
// Call whenever a window's position is changed outside the normal retile path
// (e.g. pushed offscreen during fullscreen) so the next retile does not find a
// stale cache hit and skip configure_window. The border entry is preserved.
pub fn invalidateGeomCache(window_id: u32) void {
    const s = getState();
    if (s.cache.getPtr(window_id)) |wd| wd.rect = ZERO_RECT;
}

/// Clear the workspace-valid bit for `ws_idx` so the next restoreWorkspaceGeom
/// for that workspace triggers a full retile. Used when a window's tag changes
/// for an inactive workspace without touching the current one.
pub inline fn invalidateWsGeomBit(ws_idx: u8) void {
    const s = getState();
    if (ws_idx < s.max_ws) s.ws_geom_valid &= ~wsBit(ws_idx);
}

pub inline fn dirty() void {
    getState().dirty = true;
}

// Restore windows on the current workspace to their cached tiled positions,
// bypassing the layout algorithm.
// Returns true if the cache is valid and positions have been replayed.
// Returns false if the cache is stale; caller must fall back to retileCurrentWorkspace.
pub fn restoreWorkspaceGeom(wm: *WM) bool {
    const s = getStateOpt() orelse return false;

    const ws_count = filterWorkspaceWindows(s, s.scratch_wins, null);
    const ws_windows = s.scratch_wins[0..ws_count];
    if (ws_windows.len == 0) return true;

    const current_ws = workspaces.getCurrentWorkspace() orelse return false;
    if (current_ws >= s.max_ws) return false;
    if (s.ws_geom_valid & wsBit(current_ws) == 0) return false;

    const current_screen = calculateScreenArea(wm);
    if (!layouts.rectsEqual(current_screen, s.last_retile_screen)) return false;

    // Verify every window is cached before emitting any XCB calls.
    const rects = s.scratch_rects[0..ws_windows.len];
    for (ws_windows, 0..) |win, i| {
        const wd = s.cache.get(win) orelse return false;
        if (wd.rect.width == 0 and wd.rect.height == 0) return false; // stale entry
        rects[i] = wd.rect;
    }

    for (ws_windows, rects) |win, rect| {
        utils.configureWindow(wm.conn, win, rect);
    }
    updateBorders(s, wm, ws_windows);
    return true;
}

pub inline fn isWindowTiled(window_id: u32) bool {
    const s = getStateOpt() orelse return false;
    return s.windows.contains(window_id);
}

/// Returns true only when tiling is *actively running* (runtime toggle on) AND
/// the window is managed by the tiler. Use this in handleConfigureRequest instead
/// of `wm.config.tiling.enabled and isWindowTiled(win)` so that toggling tiling
/// off at runtime actually frees applications to reposition themselves.
pub inline fn isWindowActiveTiled(window_id: u32) bool {
    const s = getStateOpt() orelse return false;
    return s.enabled and s.windows.contains(window_id);
}

fn resolveLayout(s: *State, ws_state: ?*workspaces.State, ws_idx: u8, global: bool) Layout {
    if (global) return s.layout;
    const wss = ws_state orelse return s.layout;
    return if (ws_idx < wss.workspaces.len) wss.workspaces[ws_idx].layout else s.layout;
}

inline fn makeLayoutCtx(s: *State, wm: *WM) layouts.LayoutCtx {
    return .{ .conn = wm.conn, .cache = &s.cache, .allocator = s.allocator };
}

fn dispatchLayout(layout: Layout, ctx: *const layouts.LayoutCtx, s: *State, wins: []const u32, screen: utils.Rect) void {
    const w = screen.width;
    const h = screen.height;
    const y: u16 = @intCast(screen.y);
    switch (layout) {
        .master    => master_layout.tileWithOffset(ctx, s, wins, w, h, y),
        .monocle   => monocle_layout.tileWithOffset(ctx, s, wins, w, h, y),
        .grid      => grid_layout.tileWithOffset(ctx, s, wins, w, h, y),
        .fibonacci => fibonacci_layout.tileWithOffset(ctx, s, wins, w, h, y),
    }
}

inline fn calculateScreenArea(wm: *WM) utils.Rect {
    const bar_height: u16 = if (bar.isVisible()) bar.getBarHeight() else 0;
    const bar_at_bottom   = wm.config.bar.vertical_position == .bottom;
    return .{
        .x      = 0,
        .y      = if (bar_at_bottom) 0 else @intCast(bar_height),
        .width  = wm.screen.width_in_pixels,
        .height = wm.screen.height_in_pixels -| bar_height,
    };
}

pub fn retileAllWorkspaces(wm: *WM) void {
    const s = getState();
    if (!s.enabled) return;

    const screen     = calculateScreenArea(wm);
    const ws_count   = workspaces.getWorkspaceCount();
    const current_ws = workspaces.getCurrentWorkspace() orelse return;

    const ws_state_opt = if (!wm.config.tiling.global_layout) workspaces.getState() else null;

    const ctx          = makeLayoutCtx(s, wm);
    const effective_ws = @min(ws_count, s.max_ws);

    // Zero the per-workspace fill counters.
    @memset(s.retile_lens[0..effective_ws], 0);

    for (s.windows.items()) |win| {
        const ws_idx = workspaces.getWorkspaceForWindow(win) orelse continue;
        if (ws_idx >= effective_ws) continue;
        if (s.retile_lens[ws_idx] < s.max_ws_windows) {
            s.retile_wins[ws_idx * s.max_ws_windows + s.retile_lens[ws_idx]] = win;
            s.retile_lens[ws_idx] += 1;
        }
    }

    var ws_idx: u8 = 0;
    while (ws_idx < effective_ws) : (ws_idx += 1) {
        if (ws_idx == current_ws) continue;
        if (fullscreen.getForWorkspace(ws_idx)) |_| continue;

        const n          = s.retile_lens[ws_idx];
        const ws_windows = s.retile_wins[ws_idx * s.max_ws_windows .. ws_idx * s.max_ws_windows + n];
        if (ws_windows.len == 0) continue;

        dispatchLayout(resolveLayout(s, ws_state_opt, ws_idx, wm.config.tiling.global_layout), &ctx, s, ws_windows, screen);
        updateBorders(s, wm, ws_windows);
        markWsGeomValid(s, ws_idx);
    }

    s.last_retile_screen = screen;
}

pub fn retileIfDirty(wm: *WM) void {
    const s = getState();
    if (!s.enabled or !s.dirty) return;
    retileCurrentWorkspace(wm);
}

pub fn retileCurrentWorkspace(wm: *WM) void {
    const s = getState();
    if (!s.enabled) {
        // Tiling is disabled at runtime but windows are still tracked in
        // s.windows.  The workspace switcher routes them through this function
        // for restore, so we must bring them back to their last known on-screen
        // positions via the geometry cache instead of running the layout engine.
        // restoreWorkspaceGeom is a no-op when the cache is missing or stale,
        // so there is no risk of clobbering an already-correct state.
        _ = restoreWorkspaceGeom(wm);
        return;
    }
    retile(wm, calculateScreenArea(wm), null);
    s.dirty = false;
}

/// Retile a specific inactive workspace so its geometry cache is correct before
/// the user switches to it.
///
/// MUST be called inside a server grab: retile transiently moves windows to
/// their on-screen positions.
pub fn retileInactiveWorkspace(wm: *WM, ws_idx: u8) void {
    const s = getState();
    if (!s.enabled) return;

    const ws_state = workspaces.getState() orelse return;

    if (ws_idx == ws_state.current) {
        retileCurrentWorkspace(wm);
        return;
    }

    retile(wm, calculateScreenArea(wm), ws_idx);

    // Push windows back offscreen while their workspace is inactive.
    // Do NOT invalidate the cache: restoreWorkspaceGeom will find the
    // ws_geom_valid bit set, a complete cache, and a matching screen rect,
    // and replay positions in one batch.
    for (ws_state.workspaces[ws_idx].windows.items()) |win| {
        _ = xcb.xcb_configure_window(wm.conn, win,
            xcb.XCB_CONFIG_WINDOW_X,
            &[_]u32{@bitCast(@as(i32, constants.OFFSCREEN_X_POSITION))});
    }
}

// Core retile. `for_ws`: when non-null, process that specific workspace instead
// of the current one.
fn retile(wm: *WM, screen: utils.Rect, for_ws: ?u8) void {
    const s = getState();

    const target_ws: u8 = for_ws orelse
        @intCast(workspaces.getCurrentWorkspace() orelse return);

    if (fullscreen.getForWorkspace(target_ws)) |_| return;

    const ws_count = filterWorkspaceWindows(s, s.scratch_wins, for_ws);
    const ws_windows = s.scratch_wins[0..ws_count];
    if (ws_windows.len == 0) return;

    const ctx = makeLayoutCtx(s, wm);
    dispatchLayout(resolveLayout(s, workspaces.getState(), target_ws, wm.config.tiling.global_layout), &ctx, s, ws_windows, screen);

    s.last_retile_screen = screen;
    updateBorders(s, wm, ws_windows);
    markWsGeomValid(s, target_ws);
}

// Send border pixel only if color changed since last send.
fn sendBorderColor(s: *State, conn: *xcb.xcb_connection_t, win: u32, color: u32) void {
    const gop = s.cache.getOrPut(s.allocator, win) catch {
        _ = xcb.xcb_change_window_attributes(conn, win, xcb.XCB_CW_BORDER_PIXEL, &[_]u32{color});
        return;
    };
    if (gop.found_existing and gop.value_ptr.border == color) return;
    gop.value_ptr.border = color;
    if (!gop.found_existing) gop.value_ptr.rect = ZERO_RECT;
    _ = xcb.xcb_change_window_attributes(conn, win, xcb.XCB_CW_BORDER_PIXEL, &[_]u32{color});
}

inline fn updateBorders(s: *State, wm: *WM, ws_windows: []const u32) void {
    for (ws_windows) |win| sendBorderColor(s, wm.conn, win, s.borderColor(win));
}

pub fn updateWindowFocus(wm: *WM, old_focused: ?u32, new_focused: ?u32) void {
    const s = getState();
    for ([2]?u32{ old_focused, new_focused }) |opt| {
        const win = opt orelse continue;
        if (!s.windows.contains(win)) continue;
        sendBorderColor(s, wm.conn, win, s.borderColor(win));
    }
}

fn moveWindowToIndex(s: *State, from_idx: usize, to_idx: usize) void {
    if (from_idx == to_idx) return;
    const current = s.windows.items();

    const temp = s.scratch_wins;
    if (current.len > temp.len) {
        debug.warn("moveWindowToIndex: too many windows ({})", .{current.len});
        return;
    }

    const win = current[from_idx];
    var j: usize = 0;
    for (current, 0..) |w, i| {
        if (i == from_idx) continue;
        if (j == to_idx) { temp[j] = win; j += 1; }
        temp[j] = w;
        j += 1;
    }
    if (to_idx >= j) { temp[j] = win; j += 1; }
    s.windows.reorder(temp[0..j]);
}

/// Locates the focused window and the current workspace's master window in the
/// ordered window list. Returns null when preconditions are not met (nothing
/// focused, not tiled, not on current workspace, or fewer than 2 windows).
const FocusMasterPos = struct { fp: usize, mp: usize, all: []const u32 };
fn findFocusMasterPos(s: *State) ?FocusMasterPos {
    const focused = focus.getFocused() orelse return null;
    if (!s.windows.contains(focused) or !workspaces.isOnCurrentWorkspace(focused)) return null;
    const all = s.windows.items();
    if (all.len < 2) return null;
    var fp: ?usize = null;
    var mp: ?usize = null;
    for (all, 0..) |win, i| {
        if (win == focused) fp = i;
        if (mp == null and workspaces.isOnCurrentWorkspace(win)) mp = i;
        if (fp != null and mp != null) break;
    }
    return .{ .fp = fp orelse return null, .mp = mp orelse return null, .all = all };
}

pub fn swapWithMaster(wm: *WM) void {
    const s = getState();
    const pos = findFocusMasterPos(s) orelse return;
    if (pos.fp == pos.mp) {
        for (pos.all[pos.mp + 1..], pos.mp + 1..) |win, i| {
            if (workspaces.isOnCurrentWorkspace(win)) { moveWindowToIndex(s, i, pos.mp); break; }
        }
    } else moveWindowToIndex(s, pos.fp, pos.mp);
    retileCurrentWorkspace(wm);
}

/// Like swapWithMaster, but focus transfers to the displaced window rather than
/// staying on the window that was moved.
pub fn swapWithMasterFocusSwap(wm: *WM) void {
    const s = getState();
    const pos = findFocusMasterPos(s) orelse return;
    var other_win: ?u32 = null;
    if (pos.fp == pos.mp) {
        // Focused is already master — swap with next window; focus follows to it.
        for (pos.all[pos.mp + 1..], pos.mp + 1..) |win, i| {
            if (workspaces.isOnCurrentWorkspace(win)) {
                other_win = win;
                moveWindowToIndex(s, i, pos.mp);
                break;
            }
        }
    } else {
        // Focused is a slave — swap into master; focus follows to the old master.
        other_win = pos.all[pos.mp];
        moveWindowToIndex(s, pos.fp, pos.mp);
    }
    retileCurrentWorkspace(wm);
    if (other_win) |win| focus.setFocus(wm, win, .tiling_operation);
}

pub fn toggleTiling(wm: *WM) void {
    const s = getState();
    s.enabled = !s.enabled;
    if (s.enabled) retileCurrentWorkspace(wm);
    debug.info("Tiling {s}", .{if (s.enabled) "enabled" else "disabled"});
}

pub fn syncLayoutFromWorkspace(ws: *const workspaces.Workspace) void {
    const s = getState();
    const layout = ws.layout;
    const needs_retile = s.layout != layout or ws.variation != null;
    s.layout = layout;
    // Apply the workspace-pinned master width when present; fall back to the
    // current global value so unvisited workspaces inherit the config default.
    if (ws.master_width) |mw| s.master_width = mw;
    // Apply the workspace-pinned variation override when present. A null
    // variation means "use the global default", so leave layout_variations alone.
    if (ws.variation) |v| {
        switch (v) {
            .master    => |mv| s.layout_variations.master  = mv,
            .monocle   => |mv| s.layout_variations.monocle = mv,
            .grid      => |gv| s.layout_variations.grid    = gv,
            .fibonacci => {},
        }
    }
    if (needs_retile) {
        s.dirty = true;
        s.ws_geom_valid = 0;
    }
}

fn applyLayout(wm: *WM, s: *State, layout: Layout) void {
    s.layout = layout;
    if (!wm.config.tiling.global_layout)
        if (workspaces.getCurrentWorkspaceObject()) |ws| { ws.layout = layout; };
    retileCurrentWorkspace(wm);
    debug.info("Layout: {s}", .{@tagName(layout)});
}

pub fn toggleLayout(wm: *WM) void {
    const s = getState();
    applyLayout(wm, s, stepCycle(s, s.layout, true));
}

pub fn toggleLayoutReverse(wm: *WM) void {
    const s = getState();
    applyLayout(wm, s, stepCycle(s, s.layout, false));
}

pub fn adjustMasterCount(wm: *WM, delta: i8) void {
    const s = getState();
    const new: i16 = @as(i16, s.master_count) + delta;
    if (new < 0) return;
    const clamped: u8 = @intCast(@min(new, 10));
    if (clamped == s.master_count) return;
    s.master_count = clamped;
    retileCurrentWorkspace(wm);
}

pub inline fn increaseMasterCount(wm: *WM) void { adjustMasterCount(wm,  1); }
pub inline fn decreaseMasterCount(wm: *WM) void { adjustMasterCount(wm, -1); }

pub fn adjustMasterWidth(wm: *WM, delta: f32) void {
    const s = getState();
    s.master_width = @max(constants.MIN_MASTER_WIDTH, @min(MAX_MASTER_WIDTH, s.master_width + delta));
    // In per-workspace layout mode, persist the new width onto the current
    // workspace so it is restored when switching back to this workspace.
    if (!wm.config.tiling.global_layout) {
        if (workspaces.getCurrentWorkspaceObject()) |ws| ws.master_width = s.master_width;
    }
    s.dirty = true;
    s.ws_geom_valid = 0;
    retileCurrentWorkspace(wm);
}

pub inline fn increaseMasterWidth(wm: *WM) void { adjustMasterWidth(wm,  0.025); }
pub inline fn decreaseMasterWidth(wm: *WM) void { adjustMasterWidth(wm, -0.025); }

pub fn cycleLayoutVariation(wm: *WM) void {
    const s = getState();
    switch (s.layout) {
        .master => {
            s.layout_variations.master = switch (s.layout_variations.master) {
                .lifo => .fifo,
                .fifo => .lifo,
            };
            debug.info("Master variation: {s}", .{@tagName(s.layout_variations.master)});
        },
        .monocle => {
            s.layout_variations.monocle = switch (s.layout_variations.monocle) {
                .gapless => .gaps,
                .gaps    => .gapless,
            };
            debug.info("Monocle variation: {s}", .{@tagName(s.layout_variations.monocle)});
        },
        .grid => {
            s.layout_variations.grid = switch (s.layout_variations.grid) {
                .rigid   => .relaxed,
                .relaxed => .rigid,
            };
            debug.info("Grid variation: {s}", .{@tagName(s.layout_variations.grid)});
        },
        .fibonacci => {
            debug.info("Fibonacci has no variations", .{});
            return;
        },
    }
    retileCurrentWorkspace(wm);
    bar.scheduleRedraw();
}

inline fn markWsGeomValid(s: *State, ws_idx: anytype) void {
    if (ws_idx < s.max_ws) s.ws_geom_valid |= wsBit(ws_idx);
}

// Collect windows belonging to the target workspace into buf.
// `for_ws`: when non-null, filter by that workspace index; when null, use current.
fn filterWorkspaceWindows(s: *State, buf: []u32, for_ws: ?u8) usize {
    var n: usize = 0;
    for (s.windows.items()) |win| {
        if (n >= buf.len) break;
        const on_ws = if (for_ws) |idx|
            workspaces.isWindowOnWorkspace(win, idx)
        else
            workspaces.isOnCurrentWorkspace(win);
        if (on_ws) { buf[n] = win; n += 1; }
    }
    return n;
}
